dict_adverbs={" एकबार में"	:'Adverb',
"अकंटक"	:'Adverb',
"अकसर"	:'Adverb',
"अकस्मात"	:'Adverb',
"अकस्मात्"	:'Adverb',
"अकारण"	:'Adverb',
"अकेला"	:'Adverb',
"अक्रमतः"	:'Adverb',
"अक्षरशः"	:'Adverb',
"अक्सर"	:'Adverb',
"अगत्या"	:'Adverb',
"अगर"	:'Adverb',
"अगल-बगल"	:'Adverb',
"अग़ल-बग़ल"	:'Adverb',
"अगली बार"	:'Adverb',
"अगले बरस"	:'Adverb',
"अगले वर्ष"	:'Adverb',
"अगले साल"	:'Adverb',
"अगुप्ततः"	:'Adverb',
"अग्रतः"	:'Adverb',
"अग्रे"	:'Adverb',
"अचक"	:'Adverb',
"अंचकैं"	:'Adverb',
"अचरज पूर्वक"	:'Adverb',
"अचरज से"	:'Adverb',
"अचरजपूर्वक"	:'Adverb',
"अचाक"	:'Adverb',
"अचाका"	:'Adverb',
"अचांचक"	:'Adverb',
"अचान"	:'Adverb',
"अचानक"	:'Adverb',
"अचिर"	:'Adverb',
"अच्छा"	:'Adverb',
"अच्छा हो कि"	:'Adverb',
"अच्छी तरह"	:'Adverb',
"अच्छी तरह से"	:'Adverb',
"अच्छे से"	:'Adverb',
"अजहुँ"	:'Adverb',
"अजहूँ"	:'Adverb',
"अजो"	:'Adverb',
"अजौं"	:'Adverb',
"अंट शंट"	:'Adverb',
"अंट संट"	:'Adverb',
"अंट-शंट"	:'Adverb',
"अंट-संट"	:'Adverb',
"अटकल से"	:'Adverb',
"अंटशंट"	:'Adverb',
"अंटसंट"	:'Adverb',
"अठगुना"	:'Adverb',
"अंड बंड"	:'Adverb',
"अंड-बंड"	:'Adverb',
"अंडबंड"	:'Adverb',
"अड़ोस-पड़ोस"	:'Adverb',
"अण्ड बण्ड"	:'Adverb',
"अण्ड-बण्ड"	:'Adverb',
"अण्डबण्ड"	:'Adverb',
"अतः"	:'Adverb',
"अंत में"	:'Adverb',
"अतएव"	:'Adverb',
"अंततः"	:'Adverb',
"अंततोगत्वा"	:'Adverb',
"अतरसों"	:'Adverb',
"अंतर्जानु"	:'Adverb',
"अंतर्बाह्य"	:'Adverb',
"अति"	:'Adverb',
"अंतिम दम तक"	:'Adverb',
"अतिरिक्त"	:'Adverb',
"अतिशीघ्र"	:'Adverb',
"अतिशीघ्रतः"	:'Adverb',
"अत्यंत"	:'Adverb',
"अत्यधिक"	:'Adverb',
"अत्यधिक प्रयत्नपूर्वक"	:'Adverb',
"अत्यन्त"	:'Adverb',
"अथ"	:'Adverb',
"अंदर"	:'Adverb',
"अंदर-बाहर"	:'Adverb',
"अंदाज में"	:'Adverb',
"अंदाज़ में"	:'Adverb',
"अंदाज से"	:'Adverb',
"अंदाज़ से"	:'Adverb',
"अंदाजन"	:'Adverb',
"अंदाज़न"	:'Adverb',
"अद्य"	:'Adverb',
"अद्यतन"	:'Adverb',
"अद्यावत्"	:'Adverb',
"अधः"	:'Adverb',
"अंधधुंध"	:'Adverb',
"अंधाधुंध"	:'Adverb',
"अधिक"	:'Adverb',
"अधिक से अधिक"	:'Adverb',
"अधिकतः"	:'Adverb',
"अधिकतर"	:'Adverb',
"अधिकार में"	:'Adverb',
"अधिकारतः"	:'Adverb',
"अधिकारपूर्वक"	:'Adverb',
"अधिकारहीनतः"	:'Adverb',
"अधिकांशतः"	:'Adverb',
"अधिकांशतया"	:'Adverb',
"अधिमानतः"	:'Adverb',
"अधीनता में"	:'Adverb',
"अधुना"	:'Adverb',
"अधो दिशा में"	:'Adverb',
"अधोमुख"	:'Adverb',
"अधोरध"	:'Adverb',
"अधोर्ध"	:'Adverb',
"अधौर्द्ध"	:'Adverb',
"अध्यक्षर"	:'Adverb',
"अनकरीब"	:'Adverb',
"अनक़रीब"	:'Adverb',
"अनघोरी"	:'Adverb',
"अनचाहे"	:'Adverb',
"अनत"	:'Adverb',
"अनंतर"	:'Adverb',
"अनन्तर"	:'Adverb',
"अनमिख"	:'Adverb',
"अनवधि"	:'Adverb',
"अनवरत"	:'Adverb',
"अनसूयतः"	:'Adverb',
"अनसोचे"	:'Adverb',
"अनहक"	:'Adverb',
"अनागतः"	:'Adverb',
"अनायास"	:'Adverb',
"अनाहक"	:'Adverb',
"अनिच्छा से"	:'Adverb',
"अनिच्छापूर्वक"	:'Adverb',
"अनिमिख"	:'Adverb',
"अनिमित्त"	:'Adverb',
"अनिमिष"	:'Adverb',
"अनिमेष"	:'Adverb',
"अनिश"	:'Adverb',
"अनुकूल"	:'Adverb',
"अनुक्षण"	:'Adverb',
"अनुदिन"	:'Adverb',
"अनुदिवस"	:'Adverb',
"अनुपद"	:'Adverb',
"अनुमानतः"	:'Adverb',
"अनुवत्सर"	:'Adverb',
"अनुसार"	:'Adverb',
"अनुसारतः"	:'Adverb',
"अनेकधा"	:'Adverb',
"अनेकशः"	:'Adverb',
"अनेरा"	:'Adverb',
"अनैसे"	:'Adverb',
"अन्करीब"	:'Adverb',
"अन्क़रीब"	:'Adverb',
"अन्त में"	:'Adverb',
"अन्ततः"	:'Adverb',
"अन्ततोगत्वा"	:'Adverb',
"अन्तर्जानु"	:'Adverb',
"अन्तर्बाह्य"	:'Adverb',
"अन्दर"	:'Adverb',
"अन्दर-बाहर"	:'Adverb',
"अन्दाजन"	:'Adverb',
"अन्दाज़न"	:'Adverb',
"अन्धधुन्ध"	:'Adverb',
"अन्धाधुन्ध"	:'Adverb',
"अन्यतः"	:'Adverb',
"अन्यत्र"	:'Adverb',
"अन्यदा"	:'Adverb',
"अन्यास"	:'Adverb',
"अन्येद्यु"	:'Adverb',
"अन्वक्ष"	:'Adverb',
"अपने आप"	:'Adverb',
"अपनेआप"	:'Adverb',
"अपराधानुसार"	:'Adverb',
"अपलक"	:'Adverb',
"अपार्थ"	:'Adverb',
"अपेक्षया"	:'Adverb',
"अपेक्षाकृत"	:'Adverb',
"अप्रतीष"	:'Adverb',
"अप्रत्यक्षतः"	:'Adverb',
"अप्रत्याशिततः"	:'Adverb',
"अप्रयत्नतः"	:'Adverb',
"अप्रसन्नतापूर्वक"	:'Adverb',
"अब"	:'Adverb',
"अब की"	:'Adverb',
"अब की बार"	:'Adverb',
"अब तक"	:'Adverb',
"अब भी"	:'Adverb',
"अबकी"	:'Adverb',
"अबतक"	:'Adverb',
"अबलग"	:'Adverb',
"अभयतः"	:'Adverb',
"अभरम"	:'Adverb',
"अभिमान से"	:'Adverb',
"अभिमानपूर्वक"	:'Adverb',
"अभिमुख"	:'Adverb',
"अभिस्थिर"	:'Adverb',
"अभी"	:'Adverb',
"अभी अभी"	:'Adverb',
"अभी तक"	:'Adverb',
"अभी भी"	:'Adverb',
"अभी ही"	:'Adverb',
"अभी-अभी"	:'Adverb',
"अभीतक"	:'Adverb',
"अभू"	:'Adverb',
"अभै"	:'Adverb',
"अभ्यधिक"	:'Adverb',
"अमदन"	:'Adverb',
"अमूमन"	:'Adverb',
"अयाचिततः"	:'Adverb',
"अयास"	:'Adverb',
"अयुगपद"	:'Adverb',
"अर्वाक"	:'Adverb',
"अलं"	:'Adverb',
"अलग"	:'Adverb',
"अलग अलग"	:'Adverb',
"अलग थलग"	:'Adverb',
"अलग से"	:'Adverb',
"अलग-अलग"	:'Adverb',
"अलग-थलग"	:'Adverb',
"अलबत्ता"	:'Adverb',
"अलम्"	:'Adverb',
"अलहदा"	:'Adverb',
"अलावा"	:'Adverb',
"अल्प"	:'Adverb',
"अल्पतः"	:'Adverb',
"अल्पशः"	:'Adverb',
"अवश्य"	:'Adverb',
"अवश्य ही"	:'Adverb',
"अवश्यमेव"	:'Adverb',
"अवसि"	:'Adverb',
"अवाक"	:'Adverb',
"अवाक्"	:'Adverb',
"अविच्छिन्न"	:'Adverb',
"अविच्छेद"	:'Adverb',
"अवितर्किक"	:'Adverb',
"अविदूर"	:'Adverb',
"अविरत"	:'Adverb',
"अविरथा"	:'Adverb',
"अविरामतः"	:'Adverb',
"अविलंब"	:'Adverb',
"अविलंबतः"	:'Adverb',
"अविलंबित"	:'Adverb',
"अविलम्ब"	:'Adverb',
"अविलम्बतः"	:'Adverb',
"अविलम्बित"	:'Adverb',
"अविश्रांत"	:'Adverb',
"अविश्रान्त"	:'Adverb',
"अवेर-सवेर"	:'Adverb',
"अव्यवस्थित"	:'Adverb',
"अव्यवस्थिततः"	:'Adverb',
"अव्वलन"	:'Adverb',
"अंशतः"	:'Adverb',
"अशिष्टतः"	:'Adverb',
"अशीघ्रतः"	:'Adverb',
"असकृत"	:'Adverb',
"असंदेह"	:'Adverb',
"असन्देह"	:'Adverb',
"असभ्यतः"	:'Adverb',
"असमय"	:'Adverb',
"असरार"	:'Adverb',
"असल में"	:'Adverb',
"असंशय"	:'Adverb',
"असालतन"	:'Adverb',
"असावधानतः"	:'Adverb',
"असावधानी से"	:'Adverb',
"असो"	:'Adverb',
"असों"	:'Adverb',
"असौभाग्यतः"	:'Adverb',
"अस्त-व्यस्त"	:'Adverb',
"अस्तव्यस्त"	:'Adverb',
"अस्तु"	:'Adverb',
"अस्पष्टतः"	:'Adverb',
"अहरह"	:'Adverb',
"अहर्निश"	:'Adverb',
"अहेतु"	:'Adverb',
"अहेतुक"	:'Adverb',
"अहोर-बहोर"	:'Adverb',
"अहोरात्र"	:'Adverb',
"आइंदा"	:'Adverb',
"आइन्दा"	:'Adverb',
"आकंठ"	:'Adverb',
"आकर्ण"	:'Adverb',
"आँख मूँदकर"	:'Adverb',
"आंख मूंदकर"	:'Adverb',
"आखन"	:'Adverb',
"आखिर"	:'Adverb',
"आख़िर"	:'Adverb',
"आखिरकार"	:'Adverb',
"आख़िरकार"	:'Adverb',
"आँखें फाड़कर"	:'Adverb',
"आँखे फाड़े"	:'Adverb',
"आँखों-ही-आँखों में"	:'Adverb',
"आगर"	:'Adverb',
"आगल"	:'Adverb',
"आगला"	:'Adverb',
"आगामी वर्ष"	:'Adverb',
"आगे"	:'Adverb',
"आगे की ओर"	:'Adverb',
"आगे पीछे"	:'Adverb',
"आगे बढ़कर"	:'Adverb',
"आगे-आगे"	:'Adverb',
"आगे-पीछे"	:'Adverb',
"आगेपीछे"	:'Adverb',
"आग्रह से"	:'Adverb',
"आग्रहपूर्वक"	:'Adverb',
"आचान"	:'Adverb',
"आज"	:'Adverb',
"आज कल"	:'Adverb',
"आज तक"	:'Adverb',
"आज-कल"	:'Adverb',
"आजकल"	:'Adverb',
"आजकाल"	:'Adverb',
"आजतक"	:'Adverb',
"आजीवन"	:'Adverb',
"आजू-बाजू"	:'Adverb',
"आज्ञानुसार"	:'Adverb',
"आज्ञापूर्वक"	:'Adverb',
"आठगुना"	:'Adverb',
"आठों पहर"	:'Adverb',
"आड़ा"	:'Adverb',
"आतंकपूर्वक"	:'Adverb',
"आतुरतावश"	:'Adverb',
"आदत के अनुसार"	:'Adverb',
"आदतन"	:'Adverb',
"आदर सहित"	:'Adverb',
"आदि"	:'Adverb',
"आदि में"	:'Adverb',
"आदेश से"	:'Adverb',
"आदेशपूर्वक"	:'Adverb',
"आदेशानुसार"	:'Adverb',
"आद्यांत"	:'Adverb',
"आद्यान्त"	:'Adverb',
"आद्योपांत"	:'Adverb',
"आद्योपान्त"	:'Adverb',
"आधार पर"	:'Adverb',
"आन बोर्ड"	:'Adverb',
"आनन-फानन में"	:'Adverb',
"आननफानन में"	:'Adverb',
"आप"	:'Adverb',
"आप से आप"	:'Adverb',
"आप-से-आप"	:'Adverb',
"आपरूप"	:'Adverb',
"आपस में"	:'Adverb',
"आपही"	:'Adverb',
"आपाततः"	:'Adverb',
"आम तौर पर"	:'Adverb',
"आमतौर पर"	:'Adverb',
"आमतौर से"	:'Adverb',
"आमने-सामने"	:'Adverb',
"आमरण"	:'Adverb',
"आमूलचूल"	:'Adverb',
"आयंदा"	:'Adverb',
"आयन्दा"	:'Adverb',
"आर पार"	:'Adverb',
"आर-पार"	:'Adverb',
"आरपार"	:'Adverb',
"आरंभ में"	:'Adverb',
"आरंभतः"	:'Adverb',
"आरम्भ में"	:'Adverb',
"आरम्भतः"	:'Adverb',
"आराम से"	:'Adverb',
"आंशिक रूप से"	:'Adverb',
"आशु"	:'Adverb',
"आश्चर्य से"	:'Adverb',
"आश्चर्यपूर्वक"	:'Adverb',
"आस"	:'Adverb',
"आस पड़ोस"	:'Adverb',
"आस पास"	:'Adverb',
"आस-पड़ोस"	:'Adverb',
"आस-पास"	:'Adverb',
"आसंग"	:'Adverb',
"आसङ्ग"	:'Adverb',
"आसते"	:'Adverb',
"आसते से"	:'Adverb',
"आसपास"	:'Adverb',
"आसानी से"	:'Adverb',
"आसौ"	:'Adverb',
"आस्ते"	:'Adverb',
"आस्ते से"	:'Adverb',
"आहिस्ता"	:'Adverb',
"आहिस्ता से"	:'Adverb',
"आहिस्ता-आहिस्ता"	:'Adverb',
"आहिस्ते"	:'Adverb',
"आहिस्ते से"	:'Adverb',
"आहिस्ते-आहिस्ते"	:'Adverb',
"इकंक"	:'Adverb',
"इकजोर"	:'Adverb',
"इकटक"	:'Adverb',
"इकट्ठा"	:'Adverb',
"इकट्ठे"	:'Adverb',
"इकतार"	:'Adverb',
"इकत्र"	:'Adverb',
"इकदम"	:'Adverb',
"इकदम से"	:'Adverb',
"इकबारगी"	:'Adverb',
"इकहाई"	:'Adverb',
"इकहाऊ"	:'Adverb',
"इकेला"	:'Adverb',
"इच्छा से"	:'Adverb',
"इच्छानुकुल"	:'Adverb',
"इच्छानुसार"	:'Adverb',
"इच्छापूर्वक"	:'Adverb',
"इत"	:'Adverb',
"इतः"	:'Adverb',
"इतउत"	:'Adverb',
"इतना"	:'Adverb',
"इतना ही"	:'Adverb',
"इतने में"	:'Adverb',
"इतमीनान से"	:'Adverb',
"इतरेतर"	:'Adverb',
"इतस्ततः"	:'Adverb',
"इतिमात्र"	:'Adverb',
"इतै"	:'Adverb',
"इत्तफाकन"	:'Adverb',
"इत्तफ़ाक़न"	:'Adverb',
"इत्ता"	:'Adverb',
"इत्तिफाकन"	:'Adverb',
"इत्तिफ़ाक़न"	:'Adverb',
"इत्थं"	:'Adverb',
"इत्थंमेव"	:'Adverb',
"इत्थे"	:'Adverb',
"इत्मिनान से"	:'Adverb',
"इत्मीनान से"	:'Adverb',
"इत्यादि"	:'Adverb',
"इत्यादिक"	:'Adverb',
"इधर"	:'Adverb',
"इधर उधर"	:'Adverb',
"इधर से उधर"	:'Adverb',
"इधर-उधर"	:'Adverb',
"इन दिनों"	:'Adverb',
"इभ"	:'Adverb',
"इम"	:'Adverb',
"इमि"	:'Adverb',
"इरादतन"	:'Adverb',
"इर्द गिर्द"	:'Adverb',
"इर्द-गिर्द"	:'Adverb',
"इर्दगिर्द"	:'Adverb',
"इव"	:'Adverb',
"इस ओर"	:'Adverb',
"इस कदर"	:'Adverb',
"इस क़दर"	:'Adverb',
"इस जगह"	:'Adverb',
"इस तरह"	:'Adverb',
"इस दरम्यान"	:'Adverb',
"इस दौरान"	:'Adverb',
"इस प्रकार"	:'Adverb',
"इस बार"	:'Adverb',
"इस बीच"	:'Adverb',
"इस वक्त"	:'Adverb',
"इस वर्ष"	:'Adverb',
"इस वास्ते"	:'Adverb',
"इस समय"	:'Adverb',
"इस साल"	:'Adverb',
"इसबार"	:'Adverb',
"इसलिए"	:'Adverb',
"इसी कारण"	:'Adverb',
"इसी क्षण"	:'Adverb',
"इसी जगह"	:'Adverb',
"इसी तरह"	:'Adverb',
"इसी प्रकार"	:'Adverb',
"इसी बीच"	:'Adverb',
"इसी वक्त"	:'Adverb',
"इसीलिए"	:'Adverb',
"इसै"	:'Adverb',
"इह"	:'Adverb',
"इहवाँ"	:'Adverb',
"इहवैं"	:'Adverb',
"इहाँ"	:'Adverb',
"ई प"	:'Adverb',
"ईंघे"	:'Adverb',
"ईदृश"	:'Adverb',
"ईदृश्"	:'Adverb',
"ईमानदारी से"	:'Adverb',
"ईर्ष्यतः"	:'Adverb',
"ईर्ष्यापूर्णतः"	:'Adverb',
"ईर्ष्यापूर्वक"	:'Adverb',
"ईर्ष्याहीनतः"	:'Adverb',
"ईसवी पूर्व"	:'Adverb',
"ईसवीपूर्व"	:'Adverb',
"ईसा पश्चात"	:'Adverb',
"ईसा पश्चात्"	:'Adverb',
"ईसा पूर्व"	:'Adverb',
"ईसापूर्व"	:'Adverb',
"ईहाँ"	:'Adverb',
"उकडू"	:'Adverb',
"उकडूँ"	:'Adverb',
"उकड़ू"	:'Adverb',
"उकड़ूँ"	:'Adverb',
"उकवाँ"	:'Adverb',
"उकुरू"	:'Adverb',
"उचका"	:'Adverb',
"उटक्कर"	:'Adverb',
"उठते-बैठते"	:'Adverb',
"उत"	:'Adverb',
"उतन"	:'Adverb',
"उत्तर"	:'Adverb',
"उत्सुकतावश"	:'Adverb',
"उदारतापूर्वक"	:'Adverb',
"उदाहरण के तौर पर"	:'Adverb',
"उदाहरण के रूप में"	:'Adverb',
"उदाहरण स्वरूप"	:'Adverb',
"उदाहरणतः"	:'Adverb',
"उदाहरणार्थ"	:'Adverb',
"उद्देश्यतः"	:'Adverb',
"उद्देश्यपूर्वक"	:'Adverb',
"उद्देश्यहीनतः"	:'Adverb',
"उद्विग्नतः"	:'Adverb',
"उद्विग्नतापूर्वक"	:'Adverb',
"उधर"	:'Adverb',
"उपरांत"	:'Adverb',
"उपरान्त"	:'Adverb',
"उपाय से"	:'Adverb',
"उपायतः"	:'Adverb',
"उभयतः"	:'Adverb',
"उमूमन"	:'Adverb',
"उम्र भर"	:'Adverb',
"उर्फ"	:'Adverb',
"उर्फ़"	:'Adverb',
"उलटा"	:'Adverb',
"उलटा पुलटा"	:'Adverb',
"उलटा सीधा"	:'Adverb',
"उलटा-पलटा"	:'Adverb',
"उलटा-पुलटा"	:'Adverb',
"उलटा-सीधा"	:'Adverb',
"उल्टा"	:'Adverb',
"उल्टा पुल्टा"	:'Adverb',
"उल्टा सीधा"	:'Adverb',
"उल्टा-पल्टा"	:'Adverb',
"उल्टा-पुल्टा"	:'Adverb',
"उल्टा-सीधा"	:'Adverb',
"उस ओर"	:'Adverb',
"उस जगह"	:'Adverb',
"उस तरह"	:'Adverb',
"उस वक्त"	:'Adverb',
"उस समय"	:'Adverb',
"उसी घड़ी"	:'Adverb',
"उसी घड़ी से"	:'Adverb',
"उसी तरह"	:'Adverb',
"उसी वक्त"	:'Adverb',
"उसी वक़्त"	:'Adverb',
"उसी वक्त से"	:'Adverb',
"उसी वक़्त से"	:'Adverb',
"उसी समय"	:'Adverb',
"उसी समय से"	:'Adverb',
"ऊँचाई पर"	:'Adverb',
"ऊपर"	:'Adverb',
"ऊपर की ओर"	:'Adverb',
"ऊपर से"	:'Adverb',
"ऊपर-नीचे"	:'Adverb',
"ऊर्द्ध्व"	:'Adverb',
"ऊर्ध्व"	:'Adverb',
"एक एक डग"	:'Adverb',
"एक ओर"	:'Adverb',
"एक के बाद एक"	:'Adverb',
"एक तरफ"	:'Adverb',
"एक तरफ़"	:'Adverb',
"एक दूसरे से"	:'Adverb',
"एक बार"	:'Adverb',
"एक बार और"	:'Adverb',
"एक बार फिर"	:'Adverb',
"एक बार में"	:'Adverb',
"एक समय"	:'Adverb',
"एक साथ"	:'Adverb',
"एक साल"	:'Adverb',
"एक-एक करके"	:'Adverb',
"एक-ब-एक"	:'Adverb',
"एकंग"	:'Adverb',
"एकजुट"	:'Adverb',
"एकटक"	:'Adverb',
"एकत्र"	:'Adverb',
"एकदम"	:'Adverb',
"एकदम से"	:'Adverb',
"एकदा"	:'Adverb',
"एकबार"	:'Adverb',
"एकबारगी"	:'Adverb',
"एकमुश्त"	:'Adverb',
"एकमेव"	:'Adverb',
"एकसाथ"	:'Adverb',
"एकाएक"	:'Adverb',
"एकाएकी"	:'Adverb',
"एकाकी"	:'Adverb',
"एडी"	:'Adverb',
"ऐन मौके पर"	:'Adverb',
"ऐन मौक़े पर"	:'Adverb',
"ऐन वक्त पर"	:'Adverb',
"ऐन वक़्त पर"	:'Adverb',
"ऐसा"	:'Adverb',
"ऐसा ही सही"	:'Adverb',
"ऐसा ही होगा"	:'Adverb',
"ऐसे"	:'Adverb',
"ऐसे ही"	:'Adverb',
"ऑन बोर्ड"	:'Adverb',
"ओर से"	:'Adverb',
"औचक"	:'Adverb',
"औसतन"	:'Adverb',
"कई बार"	:'Adverb',
"कठिनतः"	:'Adverb',
"कठिनाई से"	:'Adverb',
"कड़ा"	:'Adverb',
"कतई"	:'Adverb',
"कत्तई"	:'Adverb',
"कथनानुसार"	:'Adverb',
"कदम कदम पर"	:'Adverb',
"क़दम क़दम पर"	:'Adverb',
"क़दम ब क़दम"	:'Adverb',
"कदम-कदम पर"	:'Adverb',
"क़दम-क़दम पर"	:'Adverb',
"कदम-ब कदम"	:'Adverb',
"कदाचित"	:'Adverb',
"कदाचित्"	:'Adverb',
"कदापि"	:'Adverb',
"कब"	:'Adverb',
"कब तक"	:'Adverb',
"कब-तक"	:'Adverb',
"कबतक"	:'Adverb',
"कबहु"	:'Adverb',
"कभी"	:'Adverb',
"कभी कभार"	:'Adverb',
"कभी कभी"	:'Adverb',
"कभी न कभी"	:'Adverb',
"कभी नहीं"	:'Adverb',
"कभी भी"	:'Adverb',
"कभी भी नहीं"	:'Adverb',
"कभी-कभार"	:'Adverb',
"कभी-कभी"	:'Adverb',
"कभीकभार"	:'Adverb',
"कभीकभी"	:'Adverb',
"कम"	:'Adverb',
"कम से कम"	:'Adverb',
"कम-से-कम"	:'Adverb',
"कमतर"	:'Adverb',
"कमबेश"	:'Adverb',
"कमोबेश"	:'Adverb',
"करीने से"	:'Adverb',
"क़रीने से"	:'Adverb',
"करीनेवार"	:'Adverb',
"क़रीनेवार"	:'Adverb',
"करीब"	:'Adverb',
"क़रीब"	:'Adverb',
"क़रीब में"	:'Adverb',
"करीब-करीब"	:'Adverb',
"क़रीब-क़रीब"	:'Adverb',
"करीबन"	:'Adverb',
"क़रीबन"	:'Adverb',
"कर्मणा"	:'Adverb',
"कर्मानुसार"	:'Adverb',
"कल"	:'Adverb',
"कल-कल"	:'Adverb',
"कल-कल करते हुए"	:'Adverb',
"कलकल"	:'Adverb',
"कलकल करते हुए"	:'Adverb',
"कल्याणार्थ"	:'Adverb',
"कसकर"	:'Adverb',
"कहनानुसार"	:'Adverb',
"कहाँ"	:'Adverb',
"कहां"	:'Adverb',
"कहाँ-कहाँ"	:'Adverb',
"कहां-कहां"	:'Adverb',
"कहीं"	:'Adverb',
"कहीं और"	:'Adverb',
"कहीं न कहीं"	:'Adverb',
"कहुँ"	:'Adverb',
"कहूँ"	:'Adverb',
"कहे अनुसार"	:'Adverb',
"कहे मुताबिक"	:'Adverb',
"कहे मुताबिक़"	:'Adverb',
"कानूनन"	:'Adverb',
"क़ानूनन"	:'Adverb',
"काफी"	:'Adverb',
"काफ़ी"	:'Adverb',
"काफी कुछ"	:'Adverb',
"क़ाफी कुछ"	:'Adverb',
"काफी-कुछ"	:'Adverb',
"क़ाफी-कुछ"	:'Adverb',
"काम से"	:'Adverb',
"क़ायदे से"	:'Adverb',
"कारण से"	:'Adverb',
"कारणतः"	:'Adverb',
"कारणवश"	:'Adverb',
"कारणहीनतः"	:'Adverb',
"कालांतर में"	:'Adverb',
"काल्ह"	:'Adverb',
"काहे"	:'Adverb',
"काहे को"	:'Adverb',
"किंकर्तव्य-विमूढ़"	:'Adverb',
"किंकर्तव्यविमूढ़"	:'Adverb',
"किंकर्त्तव्य-विमूढ़"	:'Adverb',
"किंकर्त्तव्यविमूढ़"	:'Adverb',
"किंचित्"	:'Adverb',
"कितना"	:'Adverb',
"कित्ता"	:'Adverb',
"किधर"	:'Adverb',
"किस तरह"	:'Adverb',
"किस तरह से"	:'Adverb',
"किस प्रकार"	:'Adverb',
"किस प्रकार से"	:'Adverb',
"किस वास्ते"	:'Adverb',
"किस समय"	:'Adverb',
"किसलिए"	:'Adverb',
"किसी तरह"	:'Adverb',
"किसी तरह से"	:'Adverb',
"किसी भी तरह से"	:'Adverb',
"किसी भी दशा में"	:'Adverb',
"किसी भी सूरत में"	:'Adverb',
"किसी भी स्थिति में"	:'Adverb',
"किसी भी हालत में"	:'Adverb',
"किसी समय"	:'Adverb',
"क़िस्त दर क़िस्त"	:'Adverb',
"किस्त-दर-किस्त"	:'Adverb',
"किस्तवार"	:'Adverb',
"क़िस्तवार"	:'Adverb',
"किस्तों में"	:'Adverb',
"क़िस्तों में"	:'Adverb',
"किस्मत से"	:'Adverb',
"की तरह"	:'Adverb',
"की वजह से"	:'Adverb',
"कुछ"	:'Adverb',
"कुछ-कुछ"	:'Adverb',
"कुल मिलाकर"	:'Adverb',
"कुलमिलाकर"	:'Adverb',
"कुविधिपूर्वक"	:'Adverb',
"कुशलतापूर्वक"	:'Adverb',
"कुशलपूर्वक"	:'Adverb',
"कुसमय"	:'Adverb',
"कृतज्ञतापूर्वक"	:'Adverb',
"कृत्रिम रूप से"	:'Adverb',
"कृत्रिमता से"	:'Adverb',
"कृपया"	:'Adverb',
"कृपा कर के"	:'Adverb',
"कृपा करके"	:'Adverb',
"कृपा पूर्वक"	:'Adverb',
"कृपा से"	:'Adverb',
"कृपापूर्वक"	:'Adverb',
"के अतिरिक्त"	:'Adverb',
"के अलावा"	:'Adverb',
"के कारण"	:'Adverb',
"के चलते"	:'Adverb',
"के बदले"	:'Adverb',
"के बीच"	:'Adverb',
"के मध्य"	:'Adverb',
"के मध्य में"	:'Adverb',
"के मारे"	:'Adverb',
"के रूप में"	:'Adverb',
"के लिहाज से"	:'Adverb',
"के साथ"	:'Adverb',
"केंद्र में"	:'Adverb',
"केन्द्र में"	:'Adverb',
"केवल"	:'Adverb',
"कैसा भी"	:'Adverb',
"कैसे"	:'Adverb',
"कोई"	:'Adverb',
"कोना कोना"	:'Adverb',
"कोना-कोना"	:'Adverb',
"कोने कोने में"	:'Adverb',
"कोने-कोने में"	:'Adverb',
"कोमलता से"	:'Adverb',
"क्यूँकर"	:'Adverb',
"क्यों"	:'Adverb',
"क्योंकर"	:'Adverb',
"क्रम से"	:'Adverb',
"क्रमवार"	:'Adverb',
"क्रमशः"	:'Adverb',
"क्रमहीनतः"	:'Adverb',
"क्रमानुसार"	:'Adverb',
"क्रोधपूर्वक"	:'Adverb',
"क्षण-क्षण"	:'Adverb',
"क्षणक्षण"	:'Adverb',
"क्षमतानुसार"	:'Adverb',
"खचाखच"	:'Adverb',
"खट खट"	:'Adverb',
"खट से"	:'Adverb',
"खट-खट"	:'Adverb',
"खट-से"	:'Adverb',
"खटखट"	:'Adverb',
"खटा खट"	:'Adverb',
"खटा-खट"	:'Adverb',
"खटाक से"	:'Adverb',
"खटाक-से"	:'Adverb',
"खटाखट"	:'Adverb',
"खड़े बल"	:'Adverb',
"खड़े-खड़े"	:'Adverb',
"खन खन"	:'Adverb',
"खन-खन"	:'Adverb',
"खनखन"	:'Adverb',
"खामोशी से"	:'Adverb',
"ख़ामोशी से"	:'Adverb',
"खाली"	:'Adverb',
"ख़ाली"	:'Adverb',
"ख़ास तौर पर"	:'Adverb',
"खास तौर से"	:'Adverb',
"ख़ास तौर से"	:'Adverb',
"खासकर"	:'Adverb',
"ख़ासकर"	:'Adverb',
"खासतौर पर"	:'Adverb',
"ख़ासतौर पर"	:'Adverb',
"खासतौर से"	:'Adverb',
"ख़ासतौर से"	:'Adverb',
"खुद ब खुद"	:'Adverb',
"ख़ुद ब ख़ुद"	:'Adverb',
"खुद से"	:'Adverb',
"ख़ुद से"	:'Adverb',
"ख़ुद ही"	:'Adverb',
"खुद-ब-खुद"	:'Adverb',
"ख़ुद-ब-ख़ुद"	:'Adverb',
"खुद-बखुद"	:'Adverb',
"ख़ुद-बख़ुद"	:'Adverb',
"खुदबखुद"	:'Adverb',
"ख़ुदबख़ुद"	:'Adverb',
"खुल कर"	:'Adverb',
"खुलकर"	:'Adverb',
"खुले आम"	:'Adverb',
"खुले तौर पर"	:'Adverb',
"खुले-आम"	:'Adverb',
"खुलेआम"	:'Adverb',
"खुल्लम खुल्ला"	:'Adverb',
"खुल्लम-खुल्ला"	:'Adverb',
"खुल्लमखुल्ला"	:'Adverb',
"खुशी खुशी"	:'Adverb',
"ख़ुशी ख़ुशी"	:'Adverb',
"खुशी से"	:'Adverb',
"ख़ुशी से"	:'Adverb',
"खुशी-खुशी"	:'Adverb',
"ख़ुशी-ख़ुशी"	:'Adverb',
"खूब"	:'Adverb',
"ख़ूब"	:'Adverb',
"खेल खेल में"	:'Adverb',
"खेल-खेल में"	:'Adverb',
"खैर"	:'Adverb',
"ख़ैर"	:'Adverb',
"गट गट"	:'Adverb',
"गट-गट"	:'Adverb',
"गटगट"	:'Adverb',
"गटा गट"	:'Adverb',
"गटा-गट"	:'Adverb',
"गटागट"	:'Adverb',
"गत-वर्ष"	:'Adverb',
"गतवर्ष"	:'Adverb',
"गंभीर तौर पर"	:'Adverb',
"गंभीर रूप से"	:'Adverb',
"गंभीरता से"	:'Adverb',
"गंभीरतापूर्वक"	:'Adverb',
"गम गम"	:'Adverb',
"गम-गम"	:'Adverb',
"गमगम"	:'Adverb',
"गम्भीर तौर पर"	:'Adverb',
"गम्भीर रूप से"	:'Adverb',
"गम्भीरता से"	:'Adverb',
"गम्भीरतापूर्वक"	:'Adverb',
"गर्व से"	:'Adverb',
"गर्वपूर्वक"	:'Adverb',
"गलत वक्त पर"	:'Adverb',
"ग़लत वक़्त पर"	:'Adverb',
"गलत समय पर"	:'Adverb',
"ग़लत समय पर"	:'Adverb',
"गलत-सलत"	:'Adverb',
"ग़लत-सलत"	:'Adverb',
"गहराई में"	:'Adverb',
"गहराई से"	:'Adverb',
"गहरे"	:'Adverb',
"गाँव गाँव"	:'Adverb',
"गांव गांव"	:'Adverb',
"गाँव-गाँव"	:'Adverb',
"गांव-गांव"	:'Adverb',
"गाहे-गाहे"	:'Adverb',
"गाहे-ब-गाहे"	:'Adverb',
"गाहे-बगाहे"	:'Adverb',
"गिरते पड़ते"	:'Adverb',
"गिरते-पड़ते"	:'Adverb',
"गुप-चुप"	:'Adverb',
"गुप-चुप रूप से"	:'Adverb',
"गुपचुप"	:'Adverb',
"गुपचुप रूप से"	:'Adverb',
"गुप्त रूप से"	:'Adverb',
"गुप्ततः"	:'Adverb',
"गुमसुम"	:'Adverb',
"गुस्साकर"	:'Adverb',
"गुस्से में"	:'Adverb',
"गुस्से से"	:'Adverb',
"घड़ी-घड़ी"	:'Adverb',
"घर घर"	:'Adverb',
"घर-घर"	:'Adverb',
"चट"	:'Adverb',
"चट से"	:'Adverb',
"चट-से"	:'Adverb',
"चटपट"	:'Adverb',
"चटाक से"	:'Adverb',
"चटाक-से"	:'Adverb',
"चटाचट"	:'Adverb',
"चतुर्गुण"	:'Adverb',
"चप्पा-चप्पा"	:'Adverb',
"चलते"	:'Adverb',
"चहुँ ओर"	:'Adverb',
"चार गुना"	:'Adverb',
"चारगुना"	:'Adverb',
"चारनाचार"	:'Adverb',
"चारों ओर"	:'Adverb',
"चारों तरफ"	:'Adverb',
"चारों तरफ़"	:'Adverb',
"चारों दिशाओं में"	:'Adverb',
"चिंताहीनतः"	:'Adverb',
"चिंतिततः"	:'Adverb',
"चुनाँचे"	:'Adverb',
"चुनांचे"	:'Adverb',
"चुप"	:'Adverb',
"चुपके से"	:'Adverb',
"चुपके-चुपके"	:'Adverb',
"चुपचाप"	:'Adverb',
"चुस्ती से"	:'Adverb',
"चूड़ांत"	:'Adverb',
"चूड़ान्त"	:'Adverb',
"चोरी छिपे"	:'Adverb',
"चोरी-छिपे"	:'Adverb',
"चौकोर में"	:'Adverb',
"चौगुना"	:'Adverb',
"चौबारा"	:'Adverb',
"चौबीसों घंटे"	:'Adverb',
"छक छक"	:'Adverb',
"छक-छक"	:'Adverb',
"छकछक"	:'Adverb',
"छःगुना"	:'Adverb',
"छन छन"	:'Adverb',
"छन-छन"	:'Adverb',
"छनछन"	:'Adverb',
"छम छम"	:'Adverb',
"छम-छम"	:'Adverb',
"छमछम"	:'Adverb',
"छमा-छम"	:'Adverb',
"छमाछम"	:'Adverb',
"छम्मक-छैया"	:'Adverb',
"छहगुना"	:'Adverb',
"छिन-छिन"	:'Adverb',
"छिनछिन"	:'Adverb',
"छिन्न-भिन्न"	:'Adverb',
"छिपे-छिपे"	:'Adverb',
"छुक छुक"	:'Adverb',
"छुक-छुक"	:'Adverb',
"छुकछुक"	:'Adverb',
"छुन छुन"	:'Adverb',
"छुन-छुन"	:'Adverb',
"छुनछुन"	:'Adverb',
"छुप-छुपकर"	:'Adverb',
"छौगुना"	:'Adverb',
"जगह"	:'Adverb',
"जगह जगह"	:'Adverb',
"जगह जगह पर"	:'Adverb',
"जगह-जगह"	:'Adverb',
"जगह-जगह पर"	:'Adverb',
"जनम-जनम"	:'Adverb',
"जन्म से"	:'Adverb',
"जन्म-जन्म"	:'Adverb',
"जन्म-जन्मांतर"	:'Adverb',
"जन्म-जन्मान्तर"	:'Adverb',
"जन्मतः"	:'Adverb',
"जब"	:'Adverb',
"जबरदस्त"	:'Adverb',
"ज़बरदस्त"	:'Adverb',
"जबरदस्ती"	:'Adverb',
"ज़बरदस्ती"	:'Adverb',
"जबरन"	:'Adverb',
"ज़बरन"	:'Adverb',
"जबर्दस्त"	:'Adverb',
"ज़बर्दस्त"	:'Adverb',
"जबर्दस्ती"	:'Adverb',
"ज़बर्दस्ती"	:'Adverb',
"जमकर"	:'Adverb',
"जरा"	:'Adverb',
"ज़रा"	:'Adverb',
"जरा-सा"	:'Adverb',
"ज़रा-सा"	:'Adverb',
"जरूर"	:'Adverb',
"ज़रूर"	:'Adverb',
"जल्द"	:'Adverb',
"जल्द से जल्द"	:'Adverb',
"जल्द-से-जल्द"	:'Adverb',
"जल्दी"	:'Adverb',
"जल्दी से"	:'Adverb',
"जल्दी से जल्दी"	:'Adverb',
"जल्दी-जल्दी"	:'Adverb',
"जल्दी-से-जल्दी"	:'Adverb',
"जानबूझकर"	:'Adverb',
"जिज्ञासावश"	:'Adverb',
"जिंदगी भर"	:'Adverb',
"ज़िंदगी भर"	:'Adverb',
"जिस तरह"	:'Adverb',
"जिस तरह से"	:'Adverb',
"जिस तरह हो"	:'Adverb',
"जिस प्रकार"	:'Adverb',
"जिस प्रकार से"	:'Adverb',
"जी नहीं"	:'Adverb',
"जीवन भर"	:'Adverb',
"जीवनपर्यन्त"	:'Adverb',
"जुगत लगाकर"	:'Adverb',
"जैसा"	:'Adverb',
"जैसा कि"	:'Adverb',
"जैसा भी"	:'Adverb',
"जैसे"	:'Adverb',
"जैसे का तैसा"	:'Adverb',
"जैसे जैसे"	:'Adverb',
"जैसे तैसे"	:'Adverb',
"जैसे भी हो"	:'Adverb',
"जैसे हो"	:'Adverb',
"जैसे-जैसे"	:'Adverb',
"जैसे-तैसे"	:'Adverb',
"जोर से"	:'Adverb',
"ज़ोर से"	:'Adverb',
"जोर-शोर से"	:'Adverb',
"ज़ोर-शोर से"	:'Adverb',
"जोरशोर से"	:'Adverb',
"ज़ोरशोर से"	:'Adverb',
"जोरों से"	:'Adverb',
"ज़ोरों से"	:'Adverb',
"ज्यादा"	:'Adverb',
"ज़्यादा"	:'Adverb',
"ज्यादा से ज्यादा"	:'Adverb',
"ज़्यादा से ज़्यादा"	:'Adverb',
"ज्यादातर"	:'Adverb',
"ज़्यादातर"	:'Adverb',
"ज्यों का त्यों"	:'Adverb',
"ज्यों ज्यों"	:'Adverb',
"ज्यों-ज्यों"	:'Adverb',
"ज्यों-त्यों"	:'Adverb',
"झकझोरकर"	:'Adverb',
"झट"	:'Adverb',
"झट से"	:'Adverb',
"झट-से"	:'Adverb',
"झटके के साथ"	:'Adverb',
"झटके से"	:'Adverb',
"झटपट"	:'Adverb',
"झटा झट"	:'Adverb',
"झटा-झट"	:'Adverb',
"झम-झम"	:'Adverb',
"झमा-झम"	:'Adverb',
"झमाझम"	:'Adverb',
"झूठ ही"	:'Adverb',
"झूठ-मूठ"	:'Adverb',
"झूठमूठ"	:'Adverb',
"टक-टक"	:'Adverb',
"टकटकी से"	:'Adverb',
"टनाटन"	:'Adverb',
"टाँय टाँय"	:'Adverb',
"टाँय-टाँय"	:'Adverb',
"टाँयटाँय"	:'Adverb',
"टुक टुक"	:'Adverb',
"टुक-टुक"	:'Adverb',
"टुकर टुकर"	:'Adverb',
"टुकर-टुकर"	:'Adverb',
"टुकुर टुकुर"	:'Adverb',
"टुकुर-टुकुर"	:'Adverb',
"टें टें"	:'Adverb',
"टें-टें"	:'Adverb',
"टेंटें"	:'Adverb',
"टेढ़ा"	:'Adverb',
"ठगा-सा"	:'Adverb',
"ठंडे ठंडे"	:'Adverb',
"ठंडे-ठंडे"	:'Adverb',
"ठंढे ठंढे"	:'Adverb',
"ठंढे-ठंढे"	:'Adverb',
"ठसाठस"	:'Adverb',
"ठहर-ठहर कर"	:'Adverb',
"ठहर-ठहरकर"	:'Adverb',
"ठहाका"	:'Adverb',
"ठीक"	:'Adverb',
"ठीक ठाक"	:'Adverb',
"ठीक ठाक से"	:'Adverb',
"ठीक मौके पर"	:'Adverb',
"ठीक मौक़े पर"	:'Adverb',
"ठीक वक्त पर"	:'Adverb',
"ठीक वक़्त पर"	:'Adverb',
"ठीक समय पर"	:'Adverb',
"ठीक से"	:'Adverb',
"ठीक है"	:'Adverb',
"ठीक-ठाक"	:'Adverb',
"ठीक-ठाक से"	:'Adverb',
"ठीकठाक"	:'Adverb',
"ठुमक-ठुमक"	:'Adverb',
"ठुमकठुमक"	:'Adverb',
"ठुसाठुस"	:'Adverb',
"ठुँसाठुँस"	:'Adverb',
"ठेलम ठेल"	:'Adverb',
"ठेलम-ठेल"	:'Adverb',
"ठेलमठेल"	:'Adverb',
"डंके की चोट पर"	:'Adverb',
"डगमगाता"	:'Adverb',
"डगमगाता हुआ"	:'Adverb',
"डटकर"	:'Adverb',
"डींग मारते हुए"	:'Adverb',
"ढ़ग से"	:'Adverb',
"ढंग से"	:'Adverb',
"ढिंग"	:'Adverb',
"तकरीबन"	:'Adverb',
"तक़रीबन"	:'Adverb',
"तख़मीनन"	:'Adverb',
"तड़ से"	:'Adverb',
"तड़-से"	:'Adverb',
"तड़के"	:'Adverb',
"तड़ाक से"	:'Adverb',
"तड़ाक-से"	:'Adverb',
"तड़ातड़"	:'Adverb',
"तत्काल"	:'Adverb',
"तत्क्षण"	:'Adverb',
"तत्पश्चात"	:'Adverb',
"तत्पश्चात्"	:'Adverb',
"तथापि"	:'Adverb',
"तद उपरांत"	:'Adverb',
"तद उपरान्त"	:'Adverb',
"तदंतर"	:'Adverb',
"तदनंतर"	:'Adverb',
"तदनन्तर"	:'Adverb',
"तदनुकूल"	:'Adverb',
"तदनुरूप"	:'Adverb',
"तदनुसार"	:'Adverb',
"तदन्तर"	:'Adverb',
"तदुपरांत"	:'Adverb',
"तदुपरान्त"	:'Adverb',
"तदोपरांत"	:'Adverb',
"तदोपरान्त"	:'Adverb',
"तनहा"	:'Adverb',
"तनिक"	:'Adverb',
"तन्हा"	:'Adverb',
"तपाक से"	:'Adverb',
"तपाक-से"	:'Adverb',
"तब"	:'Adverb',
"तब भी"	:'Adverb',
"तब ही"	:'Adverb',
"तब ही से"	:'Adverb',
"तभी"	:'Adverb',
"तभी से"	:'Adverb',
"तरकीब से"	:'Adverb',
"तरतीब से"	:'Adverb',
"तरतीबवार"	:'Adverb',
"तरफ से"	:'Adverb',
"तरसों"	:'Adverb',
"तरह से"	:'Adverb',
"तरीके से"	:'Adverb',
"तरीक़े से"	:'Adverb',
"तल भूनकर"	:'Adverb',
"तल-भूनकर"	:'Adverb',
"तसल्ली से"	:'Adverb',
"ताउम्र"	:'Adverb',
"ताबड़तोड़"	:'Adverb',
"तिक्ख"	:'Adverb',
"तिगुना"	:'Adverb',
"तितर-बितर"	:'Adverb',
"तिबारा"	:'Adverb',
"तिरछा"	:'Adverb',
"तिरपट"	:'Adverb',
"तिर्यक"	:'Adverb',
"तीखा"	:'Adverb',
"तीन गुना"	:'Adverb',
"तीनगुना"	:'Adverb',
"तीर"	:'Adverb',
"तीव्रता से"	:'Adverb',
"तुरंत"	:'Adverb',
"तुरन्त"	:'Adverb',
"तुलना में"	:'Adverb',
"तूर्ण"	:'Adverb',
"तेज"	:'Adverb',
"तेज़"	:'Adverb',
"तेज गति से"	:'Adverb',
"तेजी से"	:'Adverb',
"तेज़ी से"	:'Adverb',
"तेबारा"	:'Adverb',
"तो भी"	:'Adverb',
"थर थर"	:'Adverb',
"थर-थर"	:'Adverb',
"थरथर"	:'Adverb',
"थोड़ा"	:'Adverb',
"थोड़ा थोड़ा"	:'Adverb',
"थोड़ा सा"	:'Adverb',
"थोड़ा-थोड़ा"	:'Adverb',
"थोड़ा-बहुत"	:'Adverb',
"थोड़ा-सा"	:'Adverb',
"थोड़ी-थोड़ी देर में"	:'Adverb',
"दनादन"	:'Adverb',
"दया से"	:'Adverb',
"दयापूर्वक"	:'Adverb',
"दर-दर"	:'Adverb',
"दर-ब-दर"	:'Adverb',
"दर-बदर"	:'Adverb',
"दरअसल"	:'Adverb',
"दरकिनार"	:'Adverb',
"दरपरदा"	:'Adverb',
"दरपेश"	:'Adverb',
"दरबदर"	:'Adverb',
"दरसाल"	:'Adverb',
"दराज"	:'Adverb',
"दराज़"	:'Adverb',
"दर्शनार्थ"	:'Adverb',
"दश गुना"	:'Adverb',
"दशगुना"	:'Adverb',
"दस गुना"	:'Adverb',
"दसगुना"	:'Adverb',
"दिन दहाड़े"	:'Adverb',
"दिन रात"	:'Adverb',
"दिन-दिन"	:'Adverb',
"दिन-पर-दिन"	:'Adverb',
"दिन-प्रतिदिन"	:'Adverb',
"दिन-ब-दिन"	:'Adverb',
"दिन-बदिन"	:'Adverb',
"दिन-रात"	:'Adverb',
"दिनदहाड़े"	:'Adverb',
"दिनदिन"	:'Adverb',
"दिनप्रतिदिन"	:'Adverb',
"दिनबदिन"	:'Adverb',
"दिनभर"	:'Adverb',
"दिनरात"	:'Adverb',
"दिनों-दिन"	:'Adverb',
"दिनोंदिन"	:'Adverb',
"दुगना"	:'Adverb',
"दुगुना"	:'Adverb',
"दुबारा"	:'Adverb',
"दुर्भाग्य से"	:'Adverb',
"दुर्भाग्यवश"	:'Adverb',
"दूना"	:'Adverb',
"दूर"	:'Adverb',
"दूर दूर"	:'Adverb',
"दूर-दूर"	:'Adverb',
"दूसरी ओर"	:'Adverb',
"दूसरी तरफ"	:'Adverb',
"दूसरी तरफ़"	:'Adverb',
"दृढ़ता से"	:'Adverb',
"दृढ़तापूर्वक"	:'Adverb',
"देर से"	:'Adverb',
"देर-सवेर"	:'Adverb',
"देरी से"	:'Adverb',
"देश-देश"	:'Adverb',
"देशभर"	:'Adverb',
"दैनंदिन"	:'Adverb',
"दैवयोग से"	:'Adverb',
"दैववश"	:'Adverb',
"दैवात्"	:'Adverb',
"दोगुना"	:'Adverb',
"दोबारा"	:'Adverb',
"दोहरा"	:'Adverb',
"द्वार-द्वार"	:'Adverb',
"द्विगुण"	:'Adverb',
"द्विगुणित"	:'Adverb',
"द्वेषपूर्वक"	:'Adverb',
"द्वेषहीनतः"	:'Adverb',
"धक धक"	:'Adverb',
"धक-धक"	:'Adverb',
"धकधक"	:'Adverb',
"धड़ाधड़"	:'Adverb',
"धड़ाम से"	:'Adverb',
"धम धम"	:'Adverb',
"धम-धम"	:'Adverb',
"धमधम"	:'Adverb',
"धर्मार्थ"	:'Adverb',
"धीमा"	:'Adverb',
"धीमे"	:'Adverb',
"धीमे से"	:'Adverb',
"धीमे-धीमे"	:'Adverb',
"धीरे"	:'Adverb',
"धीरे धीरे"	:'Adverb',
"धीरे से"	:'Adverb',
"धीरे-धीरे"	:'Adverb',
"धुक धुक"	:'Adverb',
"धुक-धुक"	:'Adverb',
"धुकधुक"	:'Adverb',
"धू धू"	:'Adverb',
"धू-धू"	:'Adverb',
"धूधू"	:'Adverb',
"ध्यान से"	:'Adverb',
"ध्यानपूर्वक"	:'Adverb',
"ध्यानहीनतः"	:'Adverb',
"न"	:'Adverb',
"नए सिरे से"	:'Adverb',
"नंगे पैर"	:'Adverb',
"नजदीक"	:'Adverb',
"नज़दीक"	:'Adverb',
"नजदीक में"	:'Adverb',
"नज़दीक में"	:'Adverb',
"नजीक"	:'Adverb',
"नतीजतन"	:'Adverb',
"नम्रतापूर्वक"	:'Adverb',
"नरसों"	:'Adverb',
"नवगुना"	:'Adverb',
"नाक की सीध में"	:'Adverb',
"नाख़ुशी से"	:'Adverb',
"नागहाँ"	:'Adverb',
"नाते"	:'Adverb',
"नाममात्र"	:'Adverb',
"नाराजगी से"	:'Adverb',
"नाराज़गी से"	:'Adverb',
"नाराजगीपूर्वक"	:'Adverb',
"नाराज़गीपूर्वक"	:'Adverb',
"नाहक"	:'Adverb',
"नाहक़"	:'Adverb',
"निकट"	:'Adverb',
"निकट में"	:'Adverb',
"निचली मंजिल पर"	:'Adverb',
"निचले तले पर"	:'Adverb',
"नित"	:'Adverb',
"नितांत"	:'Adverb',
"नितान्त"	:'Adverb',
"नित्य"	:'Adverb',
"नित्य प्रति"	:'Adverb',
"नित्यदा"	:'Adverb',
"नित्यप्रति"	:'Adverb',
"निपट"	:'Adverb',
"निमिष-मात्र"	:'Adverb',
"निमेष-मात्र"	:'Adverb',
"निम्नतः"	:'Adverb',
"नियम से"	:'Adverb',
"नियमानुसार"	:'Adverb',
"नियमिततः"	:'Adverb',
"निरंतर"	:'Adverb',
"निरन्तर"	:'Adverb',
"निरा"	:'Adverb',
"निरुद्देश्य"	:'Adverb',
"निरुद्देश्यतः"	:'Adverb',
"निर्निमिष"	:'Adverb',
"निर्निमेख"	:'Adverb',
"निर्निमेष"	:'Adverb',
"निर्बाध"	:'Adverb',
"निःशब्द"	:'Adverb',
"निशिदिन"	:'Adverb',
"निशिवासर"	:'Adverb',
"निश्चयपूर्वक"	:'Adverb',
"निश्चिततः"	:'Adverb',
"निश्चिंततः"	:'Adverb',
"निश्शब्द"	:'Adverb',
"निषेधार्थ"	:'Adverb',
"निष्कारण"	:'Adverb',
"निस-वासर"	:'Adverb',
"निसंकोच"	:'Adverb',
"निःसंकोच"	:'Adverb',
"निसंदेह"	:'Adverb',
"निःसंदेह"	:'Adverb',
"निसन्देह"	:'Adverb',
"निःसन्देह"	:'Adverb',
"निसवासर"	:'Adverb',
"निसाँक"	:'Adverb',
"निस्वार्थ"	:'Adverb',
"निःस्वार्थ"	:'Adverb',
"निस्संकोच"	:'Adverb',
"निस्संदेह"	:'Adverb',
"निस्सन्देह"	:'Adverb',
"निहायत"	:'Adverb',
"नीचे"	:'Adverb',
"नीचे से ऊपर तक"	:'Adverb',
"नीठि"	:'Adverb',
"नौगुना"	:'Adverb',
"न्यूनाधिक"	:'Adverb',
"पक्का"	:'Adverb',
"पग पग पर"	:'Adverb',
"पग-पग पर"	:'Adverb',
"पचगुना"	:'Adverb',
"पट"	:'Adverb',
"पट से"	:'Adverb',
"पट-से"	:'Adverb',
"पटाक से"	:'Adverb',
"पटाक-से"	:'Adverb',
"पट्ट"	:'Adverb',
"पद प्रति पद"	:'Adverb',
"पर सवार"	:'Adverb',
"परंपरानुसार"	:'Adverb',
"परभारे"	:'Adverb',
"परवशतः"	:'Adverb',
"परसाल"	:'Adverb',
"परसेंट"	:'Adverb',
"परसेन्ट"	:'Adverb',
"परसों"	:'Adverb',
"परस्पर"	:'Adverb',
"पराधीनतः"	:'Adverb',
"परिणाम स्वरूप"	:'Adverb',
"परिणामतः"	:'Adverb',
"परिणामस्वरूप"	:'Adverb',
"परे"	:'Adverb',
"पर्याप्त"	:'Adverb',
"पर्सेंट"	:'Adverb',
"पर्सेन्ट"	:'Adverb',
"पल पल"	:'Adverb',
"पल-पल"	:'Adverb',
"पल-भर"	:'Adverb',
"पलभर"	:'Adverb',
"पश्चतः"	:'Adverb',
"पश्चात"	:'Adverb',
"पश्चात्"	:'Adverb',
"पहले"	:'Adverb',
"पहले पहल"	:'Adverb',
"पहले से"	:'Adverb',
"पहले से ही"	:'Adverb',
"पहले ही"	:'Adverb',
"पहले-पहल"	:'Adverb',
"पहिले पहल"	:'Adverb',
"पहिले-पहल"	:'Adverb',
"पाँचगुना"	:'Adverb',
"पाछे"	:'Adverb',
"पार"	:'Adverb',
"पास"	:'Adverb',
"पास पड़ोस"	:'Adverb',
"पास में"	:'Adverb',
"पास-पड़ोस"	:'Adverb',
"पिछले बरस"	:'Adverb',
"पिछले वर्ष"	:'Adverb',
"पिछले साल"	:'Adverb',
"पिन्ना"	:'Adverb',
"पीछू"	:'Adverb',
"पीछे"	:'Adverb',
"पीछे-पीछे"	:'Adverb',
"पुनः"	:'Adverb',
"पुनः-पुनः"	:'Adverb',
"पूरा"	:'Adverb',
"पूरी तरह"	:'Adverb',
"पूरी तरह से"	:'Adverb',
"पूरे दिन"	:'Adverb',
"पूर्ण रूप से"	:'Adverb',
"पूर्णतः"	:'Adverb',
"पूर्णतया"	:'Adverb',
"पूर्णरुपेण"	:'Adverb',
"पूर्व"	:'Adverb',
"पूर्वतः"	:'Adverb',
"पूर्ववत"	:'Adverb',
"पूर्ववत्"	:'Adverb',
"पूर्वापर"	:'Adverb',
"पृथक पृथक"	:'Adverb',
"पृथक-पृथक"	:'Adverb',
"पृष्ठतः"	:'Adverb',
"पेटकैयाँ"	:'Adverb',
"पेटभर"	:'Adverb',
"पेश"	:'Adverb',
"पैदल"	:'Adverb',
"प्यार से"	:'Adverb',
"प्रकार से"	:'Adverb',
"प्रति क्षण"	:'Adverb',
"प्रतिक्षण"	:'Adverb',
"प्रतिदिन"	:'Adverb',
"प्रतिपल"	:'Adverb',
"प्रतिरूपतः"	:'Adverb',
"प्रतिवर्ष"	:'Adverb',
"प्रतिशत"	:'Adverb',
"प्रत्यक्ष"	:'Adverb',
"प्रत्यक्षतः"	:'Adverb',
"प्रत्येक दशा में"	:'Adverb',
"प्रथम"	:'Adverb',
"प्रथमतः"	:'Adverb',
"प्रयत्न से"	:'Adverb',
"प्रयत्नतः"	:'Adverb',
"प्रयत्नपूर्वक"	:'Adverb',
"प्रयत्नहीनतः"	:'Adverb',
"प्रयोजनतः"	:'Adverb',
"प्रयोजनहीनतः"	:'Adverb',
"प्रवाह की ओर"	:'Adverb',
"प्रवाह की दिशा में"	:'Adverb',
"प्रसन्नतः"	:'Adverb',
"प्रसन्नतापूर्वक"	:'Adverb',
"प्रायः"	:'Adverb',
"प्रायशः"	:'Adverb',
"प्रारंभ में"	:'Adverb',
"प्रारम्भ में"	:'Adverb',
"प्रेम से"	:'Adverb',
"प्रेमपूर्वक"	:'Adverb',
"फ़जूल"	:'Adverb',
"फजूल ही"	:'Adverb',
"फ़ज़ूल ही"	:'Adverb',
"फट से"	:'Adverb',
"फट-से"	:'Adverb',
"फटा फट"	:'Adverb',
"फटा-फट"	:'Adverb',
"फटाक से"	:'Adverb',
"फटाक- से"	:'Adverb',
"फटाफट"	:'Adverb',
"फड़ फड़"	:'Adverb',
"फड़-फड़"	:'Adverb',
"फड़फड़"	:'Adverb',
"फर फर"	:'Adverb',
"फर-फर"	:'Adverb',
"फरफर"	:'Adverb',
"फलतः"	:'Adverb',
"फलस्वरूप"	:'Adverb',
"फिजूल"	:'Adverb',
"फ़िजूल"	:'Adverb',
"फिजूल ही"	:'Adverb',
"फ़िज़ूल ही"	:'Adverb',
"फिर"	:'Adverb',
"फिर भी"	:'Adverb',
"फिर से"	:'Adverb',
"फिलहाल"	:'Adverb',
"फ़िलहाल"	:'Adverb',
"फीसद"	:'Adverb',
"फीसदी"	:'Adverb',
"फ़ीसदी"	:'Adverb',
"फुर फुर"	:'Adverb',
"फुर-फुर"	:'Adverb',
"फुरफुर"	:'Adverb',
"फुरसत से"	:'Adverb',
"फ़ुरसत से"	:'Adverb',
"फुर्ती से"	:'Adverb',
"फुर्सत से"	:'Adverb',
"फ़ुर्सत से"	:'Adverb',
"फूट-फूटकर"	:'Adverb',
"फूटफूट कर"	:'Adverb',
"फूर्ती से"	:'Adverb',
"फौरन"	:'Adverb',
"फ़ौरन"	:'Adverb',
"बखूबी"	:'Adverb',
"बख़ूबी"	:'Adverb',
"बखैर"	:'Adverb',
"बख़ैर"	:'Adverb',
"बख़ैरीय"	:'Adverb',
"बखैरीयत"	:'Adverb',
"बग-मेल"	:'Adverb',
"बगछुट"	:'Adverb',
"बगटुट"	:'Adverb',
"बगमेल"	:'Adverb',
"बगैर"	:'Adverb',
"बग़ैर"	:'Adverb',
"बजाय"	:'Adverb',
"बजे"	:'Adverb',
"बड़ा"	:'Adverb',
"बड़ी मुश्किल से"	:'Adverb',
"बढ़ा-चढ़ाकर"	:'Adverb',
"बढ़ाचढ़ाकर"	:'Adverb',
"बढ़िया"	:'Adverb',
"बतौर"	:'Adverb',
"बतौर उदाहरण"	:'Adverb',
"बदकिस्मती से"	:'Adverb',
"बदले"	:'Adverb',
"बदस्तूर"	:'Adverb',
"बदौलत"	:'Adverb',
"बनिस्बत"	:'Adverb',
"बमुश्किल"	:'Adverb',
"बरकरार"	:'Adverb',
"बरज़ोरी"	:'Adverb',
"बरबस"	:'Adverb',
"बराए मेहरबानी"	:'Adverb',
"बराबर"	:'Adverb',
"बलपूर्वक"	:'Adverb',
"बला से"	:'Adverb',
"बशर्ते कि"	:'Adverb',
"बस"	:'Adverb',
"बहरहाल"	:'Adverb',
"बहुत"	:'Adverb',
"बहुत अच्छा"	:'Adverb',
"बहुत अधिक"	:'Adverb',
"बहुत करके"	:'Adverb',
"बहुत कुछ"	:'Adverb',
"बहुत खराब"	:'Adverb',
"बहुत ख़राब"	:'Adverb',
"बहुत जल्दी"	:'Adverb',
"बहुत बार"	:'Adverb',
"बहुत बुरा"	:'Adverb',
"बहुत ही"	:'Adverb',
"बहुत-कुछ"	:'Adverb',
"बहुतेरा"	:'Adverb',
"बहुधा"	:'Adverb',
"बा-जाब्ता"	:'Adverb',
"बाइज्जत"	:'Adverb',
"बाइज़्ज़त"	:'Adverb',
"बाएँ"	:'Adverb',
"बाएँ बाज़ू"	:'Adverb',
"बाँका"	:'Adverb',
"बांका"	:'Adverb',
"बाकाइदा"	:'Adverb',
"बाक़ाइदा"	:'Adverb',
"बाकायदा"	:'Adverb',
"बाक़ायदा"	:'Adverb',
"बाद"	:'Adverb',
"बाद भी"	:'Adverb',
"बाद में"	:'Adverb',
"बाद-हवाई"	:'Adverb',
"बादहवाई"	:'Adverb',
"बाधारहित"	:'Adverb',
"बायें"	:'Adverb',
"बार बार"	:'Adverb',
"बार-बार"	:'Adverb',
"बारंबार"	:'Adverb',
"बारम्बार"	:'Adverb',
"बारहों महीने"	:'Adverb',
"बारी-बारी से"	:'Adverb',
"बारीकी से"	:'Adverb',
"बारीक़ी से"	:'Adverb',
"बारे"	:'Adverb',
"बावजूद"	:'Adverb',
"बावज़ूद"	:'Adverb',
"बाशिन्दा"	:'Adverb',
"बासऊर"	:'Adverb',
"बाहर"	:'Adverb',
"बाहर-भीतर"	:'Adverb',
"बिंदास"	:'Adverb',
"बिन बोले"	:'Adverb',
"बिना"	:'Adverb',
"बिना असुविधा"	:'Adverb',
"बिना कठिनाई"	:'Adverb',
"बिना दिक्कत"	:'Adverb',
"बिना परिश्रम"	:'Adverb',
"बिना परेशानी"	:'Adverb',
"बिना बिचारे"	:'Adverb',
"बिना बोले"	:'Adverb',
"बिना मतलब"	:'Adverb',
"बिना मुश्किल"	:'Adverb',
"बिना लाग लपेट के"	:'Adverb',
"बिना वजह"	:'Adverb',
"बिना विचारे"	:'Adverb',
"बिना शक"	:'Adverb',
"बिना सोचे समझे"	:'Adverb',
"बिन्दास"	:'Adverb',
"बिलकुल"	:'Adverb',
"बिला नागा"	:'Adverb',
"बिला नाग़ा"	:'Adverb',
"बिलानागा"	:'Adverb',
"बिलानाग़ा"	:'Adverb',
"बिलाशक"	:'Adverb',
"बिल्कुल"	:'Adverb',
"बीच बीच में"	:'Adverb',
"बीच में"	:'Adverb',
"बीच-बीच में"	:'Adverb',
"बीचम बीच"	:'Adverb',
"बीचों बीच"	:'Adverb',
"बीचों-बीच"	:'Adverb',
"बीचोबीच"	:'Adverb',
"बीचोंबीच"	:'Adverb',
"बुद्धिनुसार"	:'Adverb',
"बुनियादी तौर पर"	:'Adverb',
"बुरा"	:'Adverb',
"बुरी तरह"	:'Adverb',
"बुरी तरह से"	:'Adverb',
"बे-इंतहा"	:'Adverb',
"बे-तहाशा"	:'Adverb',
"बेआराम"	:'Adverb',
"बेइंतहा"	:'Adverb',
"बेकार"	:'Adverb',
"बेकार में"	:'Adverb',
"बेकार ही"	:'Adverb',
"बेखटक"	:'Adverb',
"बेखटके"	:'Adverb',
"बेगि"	:'Adverb',
"बेझिझक"	:'Adverb',
"बेतरतीब"	:'Adverb',
"बेतरीक़े"	:'Adverb',
"बेतहाशा"	:'Adverb',
"बेधड़क"	:'Adverb',
"बेपनाह"	:'Adverb',
"बेमतलब"	:'Adverb',
"बेमन से"	:'Adverb',
"बेमने"	:'Adverb',
"बेमौके"	:'Adverb',
"बेवक्त"	:'Adverb',
"बेवक़्त"	:'Adverb',
"बेवजह"	:'Adverb',
"बेशक"	:'Adverb',
"बेसाख्ता"	:'Adverb',
"बेसोचे"	:'Adverb',
"बेसोचे समझे"	:'Adverb',
"बेहतर"	:'Adverb',
"बेहद"	:'Adverb',
"बेहिचक"	:'Adverb',
"भक भक"	:'Adverb',
"भक-भक"	:'Adverb',
"भकभक"	:'Adverb',
"भर"	:'Adverb',
"भर में"	:'Adverb',
"भरपूर"	:'Adverb',
"भरपेट"	:'Adverb',
"भरसक"	:'Adverb',
"भरे गले से"	:'Adverb',
"भरोसे"	:'Adverb',
"भला"	:'Adverb',
"भली भाँति"	:'Adverb',
"भली भांति"	:'Adverb',
"भली-भाँति"	:'Adverb',
"भली-भांति"	:'Adverb',
"भलीभाँति"	:'Adverb',
"भलीभांति"	:'Adverb',
"भले ही"	:'Adverb',
"भविष्य काल में"	:'Adverb',
"भविष्य में"	:'Adverb',
"भाग्य से"	:'Adverb',
"भाग्यवश"	:'Adverb',
"भिनसहरे"	:'Adverb',
"भिनसारे"	:'Adverb',
"भी"	:'Adverb',
"भीतर"	:'Adverb',
"भीतर-बाहर"	:'Adverb',
"भुलाकर"	:'Adverb',
"भूत में"	:'Adverb',
"भौंचक्का"	:'Adverb',
"मजबूती से"	:'Adverb',
"मज़बूती से"	:'Adverb',
"मजबूरन"	:'Adverb',
"मत"	:'Adverb',
"मतिनुसार"	:'Adverb',
"मतिपूर्व"	:'Adverb',
"मंद-मंद"	:'Adverb',
"मद्देनजर"	:'Adverb',
"मद्देनज़र"	:'Adverb',
"मध्य में"	:'Adverb',
"मनसा"	:'Adverb',
"मन्द-मन्द"	:'Adverb',
"मर-मरकर"	:'Adverb',
"मरणोत्तर"	:'Adverb',
"मरणोपरांत"	:'Adverb',
"मरणोपरान्त"	:'Adverb',
"मसलन"	:'Adverb',
"महज़"	:'Adverb',
"महा"	:'Adverb',
"माँगकर"	:'Adverb',
"मात्र"	:'Adverb',
"माथे"	:'Adverb',
"माफिक"	:'Adverb',
"माफिक़"	:'Adverb',
"मारे"	:'Adverb',
"मिलकर"	:'Adverb',
"मुआफिक"	:'Adverb',
"मुआफ़िक़"	:'Adverb',
"मुकाबले"	:'Adverb',
"मुक़ाबले"	:'Adverb',
"मुख्य तौर पर"	:'Adverb',
"मुख्य रूप से"	:'Adverb',
"मुख्यतः"	:'Adverb',
"मुख्यतौर पर"	:'Adverb',
"मुताबिक"	:'Adverb',
"मुताबिक़"	:'Adverb',
"मुताबिक़"	:'Adverb',
"मुत्तसिल"	:'Adverb',
"मुलायमियत से"	:'Adverb',
"मुश्किल से"	:'Adverb',
"मुस्तैदी से"	:'Adverb',
"मुँह उठाए"	:'Adverb',
"मुहुर्मुहुः"	:'Adverb',
"मूल रूप से"	:'Adverb',
"मूलत"	:'Adverb',
"मूलतः"	:'Adverb',
"मृत्युपर्यन्त"	:'Adverb',
"मृत्यूपरांत"	:'Adverb',
"मृत्यूपरान्त"	:'Adverb',
"मेहरबानी करके"	:'Adverb',
"मौका-बेमौका"	:'Adverb',
"मौक़ा-बेमौक़ा"	:'Adverb',
"मौन"	:'Adverb',
"मौनतः"	:'Adverb',
"यकायक"	:'Adverb',
"यकीनन"	:'Adverb',
"यक़ीनन"	:'Adverb',
"यत्किंचित्"	:'Adverb',
"यथा-मति"	:'Adverb',
"यथाकर्म"	:'Adverb',
"यथाक्रम"	:'Adverb',
"यथाक्षम"	:'Adverb',
"यथानियम"	:'Adverb',
"यथापराध"	:'Adverb',
"यथापूर्व"	:'Adverb',
"यथाभीष्ट"	:'Adverb',
"यथामति"	:'Adverb',
"यथावकाश"	:'Adverb',
"यथावत"	:'Adverb',
"यथावत्"	:'Adverb',
"यथावांछित"	:'Adverb',
"यथाविधि"	:'Adverb',
"यथाशक्ति"	:'Adverb',
"यथासंभव"	:'Adverb',
"यथासमय"	:'Adverb',
"यथासाध्य"	:'Adverb',
"यथास्थान"	:'Adverb',
"यथेच्छ"	:'Adverb',
"यथेष्ट"	:'Adverb',
"यदा"	:'Adverb',
"यदा-कदा"	:'Adverb',
"यदाकदा"	:'Adverb',
"यदि"	:'Adverb',
"यहाँ"	:'Adverb',
"यहां"	:'Adverb',
"यहाँ पर"	:'Adverb',
"यहाँ वहाँ"	:'Adverb',
"यहाँ से वहाँ"	:'Adverb',
"यहाँ-वहाँ"	:'Adverb',
"यहां-वहां"	:'Adverb',
"यहीं"	:'Adverb',
"याचिततः"	:'Adverb',
"युक्तिपूर्वक"	:'Adverb',
"यूँ"	:'Adverb',
"यूँ ही"	:'Adverb',
"येन केन प्रकारेण"	:'Adverb',
"यों"	:'Adverb',
"यों ही"	:'Adverb',
"यौं ही"	:'Adverb',
"रंचमात्र"	:'Adverb',
"रत्तीभर"	:'Adverb',
"रफ्ता-रफ्ता"	:'Adverb',
"रफ्तार से"	:'Adverb',
"रफ़्तार से"	:'Adverb',
"रह रह कर"	:'Adverb',
"रह रहकर"	:'Adverb',
"रह-रह कर"	:'Adverb',
"रह-रहकर"	:'Adverb',
"रात-दिन"	:'Adverb',
"रातदिन"	:'Adverb',
"रातों-रात"	:'Adverb',
"रातोंरात"	:'Adverb',
"राष्ट्र-राष्ट्र"	:'Adverb',
"रिम-झिम"	:'Adverb',
"रिमझिम"	:'Adverb',
"रिमझिम-रिमझिम"	:'Adverb',
"रुक रुककर"	:'Adverb',
"रुक-रुक कर"	:'Adverb',
"रुक-रुककर"	:'Adverb',
"रुँधे गले से"	:'Adverb',
"रू-ब-रू"	:'Adverb',
"रू-बरू"	:'Adverb',
"रूबरू"	:'Adverb',
"रोज"	:'Adverb',
"रोज़"	:'Adverb',
"रोजमर्रा"	:'Adverb',
"रोज़मर्रा"	:'Adverb',
"रोजाना"	:'Adverb',
"रोज़ाना"	:'Adverb',
"लगनपूर्वक"	:'Adverb',
"लगभग"	:'Adverb',
"लगातार"	:'Adverb',
"लगे हाथ"	:'Adverb',
"लटपटाता"	:'Adverb',
"लटपटाता हुआ"	:'Adverb',
"लड़खड़ाता"	:'Adverb',
"लड़खड़ाता हुआ"	:'Adverb',
"लपक"	:'Adverb',
"लपककर"	:'Adverb',
"लंब"	:'Adverb',
"लबरेज"	:'Adverb',
"लबरेज़"	:'Adverb',
"लंबवत"	:'Adverb',
"लंबवत्"	:'Adverb',
"लबालब"	:'Adverb',
"लम्ब"	:'Adverb',
"लम्बवत"	:'Adverb',
"लम्बवत्"	:'Adverb',
"लाख"	:'Adverb',
"लापरवाही से"	:'Adverb',
"लिहाजा"	:'Adverb',
"लिहाज़ा"	:'Adverb',
"लेशमात्र"	:'Adverb',
"लौटानी"	:'Adverb',
"वकालतन"	:'Adverb',
"वक्त-बेवक्त"	:'Adverb',
"वक़्त-बेवक़्त"	:'Adverb',
"वक्तन्-फौवक्तन्"	:'Adverb',
"वगैरह"	:'Adverb',
"वग़ैरह"	:'Adverb',
"वगैरा"	:'Adverb',
"वचसा"	:'Adverb',
"वजह से"	:'Adverb',
"वन्स मोर"	:'Adverb',
"वरीयता से"	:'Adverb',
"वर्गाकार में"	:'Adverb',
"वर्तमान में"	:'Adverb',
"वर्ष भर"	:'Adverb',
"वर्षभर"	:'Adverb',
"वस्तुतः"	:'Adverb',
"वहाँ"	:'Adverb',
"वहीं"	:'Adverb',
"वाकई"	:'Adverb',
"वाक़ई"	:'Adverb',
"वाचा"	:'Adverb',
"वापस"	:'Adverb',
"वापस से"	:'Adverb',
"वापिस"	:'Adverb',
"वाशिन्दा"	:'Adverb',
"वास्तव में"	:'Adverb',
"विचारपूर्वक"	:'Adverb',
"विचारहीनतः"	:'Adverb',
"विचारिततः"	:'Adverb',
"विधानतः"	:'Adverb',
"विधिपूर्वक"	:'Adverb',
"विधिवत"	:'Adverb',
"विधिवत्"	:'Adverb',
"विधिहीनतः"	:'Adverb',
"विनम्रता से"	:'Adverb',
"विनम्रतापूर्वक"	:'Adverb',
"विनयपूर्वक"	:'Adverb',
"विरामतः"	:'Adverb',
"विलंबतः"	:'Adverb',
"विलंबपूर्वक"	:'Adverb',
"विवश होकर"	:'Adverb',
"विवशतः"	:'Adverb',
"विशिष्टतः"	:'Adverb',
"विशेष"	:'Adverb',
"विशेष रूप से"	:'Adverb',
"विशेषकर"	:'Adverb',
"विशेषतः"	:'Adverb',
"विश्वसनीयता से"	:'Adverb',
"विश्वास के साथ"	:'Adverb',
"विश्वासपूर्वक"	:'Adverb',
"विस्तार से"	:'Adverb',
"विस्तारपूर्वक"	:'Adverb',
"विस्मय से"	:'Adverb',
"वृथा"	:'Adverb',
"वैसा"	:'Adverb',
"वैसे"	:'Adverb',
"वैसे का वैसा"	:'Adverb',
"व्यर्थ"	:'Adverb',
"व्यर्थ ही"	:'Adverb',
"व्यवस्थापूर्वक"	:'Adverb',
"व्यवस्थिततः"	:'Adverb',
"शत-प्रतिशत"	:'Adverb',
"शब्दशः"	:'Adverb',
"शर्तिया"	:'Adverb',
"शहर-शहर"	:'Adverb',
"शांत"	:'Adverb',
"शांति से"	:'Adverb',
"शांतिपूर्वक"	:'Adverb',
"शान्त"	:'Adverb',
"शान्ति से"	:'Adverb',
"शान्तिपूर्वक"	:'Adverb',
"शायद"	:'Adverb',
"शालीनतः"	:'Adverb',
"शिताब"	:'Adverb',
"शिष्टतः"	:'Adverb',
"शिष्टता से"	:'Adverb',
"शिष्टतापूर्वक"	:'Adverb',
"शिष्टाचारपूर्वक"	:'Adverb',
"शिष्टाचारहीनतः"	:'Adverb',
"शीघ्र"	:'Adverb',
"शीघ्रतः"	:'Adverb',
"शीघ्रता से"	:'Adverb',
"शीघ्रतापूर्वक"	:'Adverb',
"शुद्ध रूप से"	:'Adverb',
"शुरुआत में"	:'Adverb',
"शुरुवात में"	:'Adverb',
"शुरू में"	:'Adverb',
"शुरू शुरू में"	:'Adverb',
"शुरू-शुरू में"	:'Adverb',
"शेखी मारते हुए"	:'Adverb',
"शौक से"	:'Adverb',
"शौकिया"	:'Adverb',
"संकल्पपूर्वक"	:'Adverb',
"सकारात्मक रूप से"	:'Adverb',
"सकारे"	:'Adverb',
"सकुशल"	:'Adverb',
"संकोचहीनतः"	:'Adverb',
"सख्त"	:'Adverb',
"सख़्त"	:'Adverb',
"संग संग"	:'Adverb',
"संग-संग"	:'Adverb',
"सगर्व"	:'Adverb',
"सच में"	:'Adverb',
"सच-सच"	:'Adverb',
"सचमुच"	:'Adverb',
"सच्चाई से"	:'Adverb',
"सच्ची मुच्ची"	:'Adverb',
"सच्ची-मुच्ची"	:'Adverb',
"सतगुना"	:'Adverb',
"सतत"	:'Adverb',
"सतत्"	:'Adverb',
"सतह पर"	:'Adverb',
"सत्कारपूर्वक"	:'Adverb',
"सत्यतः"	:'Adverb',
"सदा"	:'Adverb',
"सदा सदा"	:'Adverb',
"सदा-सदा"	:'Adverb',
"संदिग्धतः"	:'Adverb',
"सदेह"	:'Adverb',
"सदैव"	:'Adverb',
"सद्य"	:'Adverb',
"सन्निकट"	:'Adverb',
"सपत्नीक"	:'Adverb',
"सपरिवार"	:'Adverb',
"संपूर्णतः"	:'Adverb',
"संपूर्णतया"	:'Adverb',
"संप्रति"	:'Adverb',
"सप्रयोजन"	:'Adverb',
"सब मिलाकर"	:'Adverb',
"सबमिलाकर"	:'Adverb',
"सबसे पहले"	:'Adverb',
"सबेर"	:'Adverb',
"सबेरे"	:'Adverb',
"संभवतः"	:'Adverb',
"संभालकर"	:'Adverb',
"सभी तरफ़"	:'Adverb',
"सभ्यतः"	:'Adverb',
"सभ्यतापूर्वक"	:'Adverb',
"समक्ष"	:'Adverb',
"समझ बूझ कर"	:'Adverb',
"समझ-बूझकर"	:'Adverb',
"समय आने पर"	:'Adverb',
"समय समय पर"	:'Adverb',
"समय-कुसमय"	:'Adverb',
"समय-समय पर"	:'Adverb',
"समयानुसार"	:'Adverb',
"समांतर"	:'Adverb',
"समानांतर"	:'Adverb',
"समानान्तर"	:'Adverb',
"समान्तर"	:'Adverb',
"समीप"	:'Adverb',
"समूहतः"	:'Adverb',
"समेत"	:'Adverb',
"सम्प्रति"	:'Adverb',
"सम्भवतः"	:'Adverb',
"सम्भालकर"	:'Adverb',
"सम्मुख"	:'Adverb',
"संयुक्त रूप से"	:'Adverb',
"संयोगवश"	:'Adverb',
"संयोगवशात्"	:'Adverb',
"सर सर"	:'Adverb',
"सर-सर"	:'Adverb',
"सरपट"	:'Adverb',
"सरलतः"	:'Adverb',
"सरलता से"	:'Adverb',
"सरसर"	:'Adverb',
"सरसरी"	:'Adverb',
"सरासर"	:'Adverb',
"सरे आम"	:'Adverb',
"सरे-आम"	:'Adverb',
"सरेआम"	:'Adverb',
"सरेशाम"	:'Adverb',
"सर्व प्रथम"	:'Adverb',
"सर्वतोभाव"	:'Adverb',
"सर्वत्र"	:'Adverb',
"सर्वथा"	:'Adverb',
"सर्वदा"	:'Adverb',
"सर्वदैव"	:'Adverb',
"सर्वप्रथम"	:'Adverb',
"सर्वोपरि"	:'Adverb',
"सलामत"	:'Adverb',
"सलीक़े से"	:'Adverb',
"सविरामतः"	:'Adverb',
"सविस्मय"	:'Adverb',
"सवेर"	:'Adverb',
"सवेरे"	:'Adverb',
"सशरीर"	:'Adverb',
"ससमय"	:'Adverb',
"ससम्मान"	:'Adverb',
"सस्वर"	:'Adverb',
"सहजतः"	:'Adverb',
"सहजता से"	:'Adverb',
"सहर्ष"	:'Adverb',
"सहसा"	:'Adverb',
"सहारे"	:'Adverb',
"सहित"	:'Adverb',
"सही ढंग से"	:'Adverb',
"सही तरह से"	:'Adverb',
"सही मौके पर"	:'Adverb',
"सही मौक़े पर"	:'Adverb',
"सही वक्त पर"	:'Adverb',
"सही वक़्त पर"	:'Adverb',
"सही समय पर"	:'Adverb',
"सही सलामत"	:'Adverb',
"सही-सलामत"	:'Adverb',
"साक्षात"	:'Adverb',
"साक्षात्"	:'Adverb',
"सातंक"	:'Adverb',
"सातगुना"	:'Adverb',
"साथ"	:'Adverb',
"साथ में"	:'Adverb',
"साथ साथ"	:'Adverb',
"साथ ही"	:'Adverb',
"साथ ही साथ"	:'Adverb',
"साथ-साथ"	:'Adverb',
"सादर"	:'Adverb',
"सादेश"	:'Adverb',
"साधारणतः"	:'Adverb',
"साधारणतया"	:'Adverb',
"साधिकार"	:'Adverb',
"साफ"	:'Adverb',
"साफ़"	:'Adverb',
"साफ़ साफ़"	:'Adverb',
"साफ-साफ"	:'Adverb',
"साफ़-साफ़"	:'Adverb',
"साफतौर पर"	:'Adverb',
"साभार"	:'Adverb',
"साभिप्रायः"	:'Adverb',
"साभिमान"	:'Adverb',
"सामने"	:'Adverb',
"सामान्य तौर पर"	:'Adverb',
"सामान्यतः"	:'Adverb',
"सामान्यतया"	:'Adverb',
"सामूहिक रूप से"	:'Adverb',
"सायास"	:'Adverb',
"साल भर"	:'Adverb',
"साल साल"	:'Adverb',
"साल-दर-साल"	:'Adverb',
"साल-ब-साल"	:'Adverb',
"साल-बसाल"	:'Adverb',
"साल-साल"	:'Adverb',
"सालभर"	:'Adverb',
"सालों साल"	:'Adverb',
"सालों-साल"	:'Adverb',
"सावधानतः"	:'Adverb',
"सावधानी पूर्वक"	:'Adverb',
"सावधानी से"	:'Adverb',
"सावधानीपूर्वक"	:'Adverb',
"साश्चर्य"	:'Adverb',
"साश्रु"	:'Adverb',
"सासूय"	:'Adverb',
"साहसपूर्वक"	:'Adverb',
"सिताब"	:'Adverb',
"सिताबी"	:'Adverb',
"सिर्फ"	:'Adverb',
"सिर्फ़"	:'Adverb',
"सिलसिलेवार"	:'Adverb',
"सिवा"	:'Adverb',
"सिवाय"	:'Adverb',
"सीधा"	:'Adverb',
"सीधे"	:'Adverb',
"सुगमतः"	:'Adverb',
"सुगमता से"	:'Adverb',
"सुगमतापूर्वक"	:'Adverb',
"सुचारु रूप से"	:'Adverb',
"सुबह"	:'Adverb',
"सुबह सवेरे"	:'Adverb',
"सुबह-सवेरे"	:'Adverb',
"सुबह-सुबह"	:'Adverb',
"सुर-सुर"	:'Adverb',
"सुरक्षिततः"	:'Adverb',
"सुरसुर"	:'Adverb',
"सूक्ष्मतः"	:'Adverb',
"से"	:'Adverb',
"सोच विचार कर"	:'Adverb',
"सोच समझ कर"	:'Adverb',
"सोच-विचारकर"	:'Adverb',
"सोच-समझकर"	:'Adverb',
"सोते-जागते"	:'Adverb',
"सोद्देश्य"	:'Adverb',
"सौभाग्य से"	:'Adverb',
"सौभाग्यतः"	:'Adverb',
"स्थान-स्थान पर"	:'Adverb',
"स्नेहपूर्वक"	:'Adverb',
"स्पष्ट"	:'Adverb',
"स्पष्ट रूप से"	:'Adverb',
"स्पष्टतः"	:'Adverb',
"स्पष्टतया"	:'Adverb',
"स्फूर्तिपूर्वक"	:'Adverb',
"स्यात्"	:'Adverb',
"स्वगत"	:'Adverb',
"स्वतः"	:'Adverb',
"स्वतः से"	:'Adverb',
"स्वतंत्र रूप से"	:'Adverb',
"स्वभाव के अनुसार"	:'Adverb',
"स्वभावतः"	:'Adverb',
"स्वयं से"	:'Adverb',
"स्वातंत्रोत्तर"	:'Adverb',
"स्वांतःसुखाय"	:'Adverb',
"स्वाधीनतः"	:'Adverb',
"स्वान्तःसुखाय"	:'Adverb',
"स्वीकारात्मक रूप से"	:'Adverb',
"स्वेच्छतः"	:'Adverb',
"स्वेच्छया"	:'Adverb',
"स्वेच्छा से"	:'Adverb',
"स्वेच्छापूर्वक"	:'Adverb',
"स्वेच्छार्थ"	:'Adverb',
"हकीकत में"	:'Adverb',
"हक़ीक़त में"	:'Adverb',
"हकीकतन"	:'Adverb',
"हक़ीक़तन"	:'Adverb',
"हक्का-बक्का"	:'Adverb',
"हतबुद्धि"	:'Adverb',
"हमेशा"	:'Adverb',
"हमेशा की तरह"	:'Adverb',
"हर कदम पर"	:'Adverb',
"हर क़दम पर"	:'Adverb',
"हर कोना"	:'Adverb',
"हर कोने में"	:'Adverb',
"हर क्षण"	:'Adverb',
"हर घड़ी"	:'Adverb',
"हर जगह"	:'Adverb',
"हर दशा में"	:'Adverb',
"हर दिन"	:'Adverb',
"हर पग पर"	:'Adverb',
"हर रोज"	:'Adverb',
"हर रोज़"	:'Adverb',
"हर वक्त"	:'Adverb',
"हर वक़्त"	:'Adverb',
"हर संभव"	:'Adverb',
"हर समय"	:'Adverb',
"हर सम्भव"	:'Adverb',
"हर साल"	:'Adverb',
"हर सूरत में"	:'Adverb',
"हर हालत में"	:'Adverb',
"हरगिज"	:'Adverb',
"हरगिज़"	:'Adverb',
"हरघड़ी"	:'Adverb',
"हरदम"	:'Adverb',
"हरसंभव"	:'Adverb',
"हरसम्भव"	:'Adverb',
"हरसाल"	:'Adverb',
"हर्षपूर्वक"	:'Adverb',
"हल्का सा"	:'Adverb',
"हल्का-सा"	:'Adverb',
"हवा की ओर"	:'Adverb',
"हवा की तरफ"	:'Adverb',
"हवा के अनुकूल"	:'Adverb',
"हवानुकूल"	:'Adverb',
"हस्तचालन द्वारा"	:'Adverb',
"हस्ब-ए-मामूल"	:'Adverb',
"हस्बे-मामूल"	:'Adverb',
"हस्बेमामूल"	:'Adverb',
"हाथ द्वारा"	:'Adverb',
"हाथ में"	:'Adverb',
"हाथ से"	:'Adverb',
"हाथा-हाथी"	:'Adverb',
"हाथों मे"	:'Adverb',
"हाथो हाथ"	:'Adverb',
"हाथों हाथ"	:'Adverb',
"हाथो-हाथ"	:'Adverb',
"हाथों-हाथ"	:'Adverb',
"हितार्थ"	:'Adverb',
"हिसाब"	:'Adverb',
"हुआँ"	:'Adverb',
"हू-ब-हू"	:'Adverb',
"हूबहू"	:'Adverb',
"हैरत से"	:'Adverb',
"हैरानी से"	:'Adverb',
"होते हवाते"	:'Adverb',
"होले-होले"	:'Adverb',
"हौले"	:'Adverb',
"हौले से"	:'Adverb',
"हौले-हौले"	:'Adverb',

}