dict_conjunct={'तो'	:'Conjunct',"जबकि":'Conjunct',"या":'Conjunct',"एंव":'Conjunct',
'और'	:'Conjunct',
'एवं'	:'Conjunct',
'यानि'	:'Conjunct',
'यदि'	:'Conjunct',
'कि'	:'Conjunct',
'व'	:'Conjunct',
'ताकि'	:'Conjunct',
'चूंकि'	:'Conjunct',
'तथा':'Conjunct',
'अथवा'	:'Conjunct',
'लेकिन'	:'Conjunct',
'यानी'	:'Conjunct',
'क्योेंकि'	:'Conjunct',
'बल्कि'	:'Conjunct',
                   "जहा": 'Conjunct',
                   "जहां": 'Conjunct',
                   "जहाँ": 'Conjunct',
                   "जिधर": 'Conjunct',
                   "किस जगह": 'Conjunct',
                   "जिस जगह": 'Conjunct',
                   "कहां": 'Conjunct',
                   "किधर": 'Conjunct',
                   "कहाँ": 'Conjunct',
                   "कैसे": 'Conjunct',

    }