dict_date_month_noun={"संडे"	:'Date_Month_N',
"मंडे"	:'Date_Month_N',
"ट्यूसडे"	:'Date_Month_N',
"वेडनेसडे"	:'Date_Month_N',
"थूरसदय"	:'Date_Month_N',
"फ्राइडे"	:'Date_Month_N',
"सटरडे"	:'Date_Month_N',
"रविवार"	:'Date_Month_N',
"सोमवार"	:'Date_Month_N',
"मंगलवार"	:'Date_Month_N',
"बुधवार"	:'Date_Month_N',
"गुरुवार"	:'Date_Month_N',
"शुक्रवार"	:'Date_Month_N',
"शनिवार"	:'Date_Month_N',
"जनवरी"	:'Date_Month_N',
"फ़रवरी"	:'Date_Month_N',
"मार्च"	:'Date_Month_N',
"अप्रैल"	:'Date_Month_N',
"मई"	:'Date_Month_N',
"जून"	:'Date_Month_N',
"जुलाई"	:'Date_Month_N',
"अगस्त"	:'Date_Month_N',
"सितम्बर"	:'Date_Month_N',
"अकतूबर"	:'Date_Month_N',
"नवंबर"	:'Date_Month_N',
"दिसम्बर"	:'Date_Month_N',

}