dict_determiner={"हर कोई"	:'Quantifier',
"सभी सब"	:'Quantifier',
"प्रत्येक हर एक"	:'Quantifier',
"दोनों"	:'Quantifier',
"काफी"	:'Quantifier',
"पूरा"	:'Quantifier',
"आधा"	:'Quantifier',
"एक चौथाई"	:'Quantifier',
"पूरा"	:'Quantifier',
"ज़्यादा "	:'Quantifier',
"कम"	:'Quantifier',
"कई"	:'Quantifier',
"ज़्यादा"	:'Quantifier',
}