dict_possesive_pronoun={"मेरा"	:'Possesive_pro',"इनकी":'Possesive_pro',"उनकी":'Possessive_pro',
"मेरी"	:'Possesive_pro',
"मेरे"	:'Possesive_pro',
"मेरी"	:'Possesive_pro',
"तेरा"	:'Possesive_pro',
"तेरी"	:'Possesive_pro',
"तेरे"	:'Possesive_pro',
"तेरी"	:'Possesive_pro',
"तुम्हारा"	:'Possesive_pro',
"तुम्हारी"	:'Possesive_pro',
"तुम्हारे"	:'Possesive_pro',
"आपका"	:'Possesive_pro',
"आपकी"	:'Possesive_pro',
"अपने":'Possesive_pro',
"आपके"	:'Possesive_pro',
"इसका"	:'Possesive_pro',
"उसका"	:'Possesive_pro',
"आपको" : 'Possesive_pro',
"इसकी"	:'Possesive_pro',
"उसकी"	:'Possesive_pro',
"इसके"	:'Possesive_pro',
"उसके"	:'Possesive_pro',
"हमारा"	:'Possesive_pro',
"हमारी"	:'Possesive_pro',
"हमारे"	:'Possesive_pro',
"उसको"  :'Possesive_pro',
"उसने":'Possesive_pro',
"अपनी":'Possesive_pro',
}