dict_possesive_pronoun_1={"मेरा"	:'Pronoun',"इनकी":'Pronoun',"उनकी":'Pronoun',
"मेरी"	:'Pronoun',
"मेरे"	:'Pronoun',
"मेरी"	:'Pronoun',
"तेरा"	:'Pronoun',
"तेरी"	:'Pronoun',
"तेरे"	:'Pronoun',
"तेरी"	:'Pronoun',
"तुम्हारा"	:'Pronoun',
"तुम्हारी"	:'Pronoun',
"तुम्हारे"	:'Pronoun',
"आपका"	:'Pronoun',
"आपकी"	:'Pronoun',
"अपने":'Pronoun',
"आपके"	:'Pronoun',
"इसका"	:'Pronoun',
"उसका"	:'Pronoun',
"आपको" : 'Pronoun',
"इसकी"	:'Pronoun',
"उसकी"	:'Pronoun',
"इसके"	:'Pronoun',
"उसके"	:'Pronoun',
"हमारा"	:'Pronoun',
"हमारी"	:'Pronoun',
"हमारे"	:'Pronoun',
"उसको"  :'Pronoun',
"उसने":'Pronoun',
"अपनी":'Pronoun',
}