dict_preposition={"अगला"	:'Preposition',"ने":'Preposition',"ले":'Preposition',"टू":'Preposition',"इससे":'Preposition',
"अंदर"	:'Preposition',"को":'Preposition',"वाले":'Preposition',
"अधीन "	:'Preposition',
"अपेक्षा"	:'Preposition',
"आगे"	:'Preposition',
"आर-पार"	:'Preposition',
"आस-पास"	:'Preposition',
"उल्टा"	:'Preposition',
"ऊपर"	:'Preposition',
"ऐसा"	:'Preposition',
"ओर"	:'Preposition',
"का"	:'Preposition',
"कारण"	:'Preposition',
"की"	:'Preposition',
"की ओर"	:'Preposition',
"की ओर से"	:'Preposition',
"की वजह से"	:'Preposition',
"के"	:'Preposition',
"के अतिरिक्त"	:'Preposition',
"के अंदर"	:'Preposition',
"के अनुसार"	:'Preposition',
"के अलावा"	:'Preposition',
"के ऊपर"	:'Preposition',
"के कारण"	:'Preposition',
"के खिलाफ"	:'Preposition',
"के पार"	:'Preposition',
"के पास"	:'Preposition',
"के नज़दीक"	:'Preposition',
"के पीछे"	:'Preposition',
"के बजाय"	:'Preposition',
"के बाद"	:'Preposition',
"के बाद से"	:'Preposition',
"के बारे में"	:'Preposition',
"के बावजूद"	:'Preposition',
"के बाहर"	:'Preposition',
"के बीच"	:'Preposition',
"के बीच में"	:'Preposition',
"के माध्यम से"	:'Preposition',
"के लिए"	:'Preposition',
"के शीर्ष पर"	:'Preposition',
"के सामने"	:'Preposition',
"चारों ओर"	:'Preposition',
"जब तक"	:'Preposition',
"जरिए"	:'Preposition',
"जहाँ तक"	:'Preposition',
"जैसा"	:'Preposition',
"जोड़"	:'Preposition',
"तक"	:'Preposition',
"तथा"	:'Preposition',
"तरफ"	:'Preposition',
"तरह"	:'Preposition',
"तीन शब्द"	:'Preposition',
"दूर"	:'Preposition',
"दूर से"	:'Preposition',
"दो शब्दों"	:'Preposition',
"दौर "	:'Preposition',
"दौरान"	:'Preposition',
"द्वारा"	:'Preposition',
"निकट"	:'Preposition',
"नीचे"	:'Preposition',
"पर"	:'Preposition',
"परे"	:'Preposition',
"पहले"	:'Preposition',
"पहले से"	:'Preposition',
"पार"	:'Preposition',
"पास"	:'Preposition',
"पीछे"	:'Preposition',
"पूर्व"	:'Preposition',
"प्रति"	:'Preposition',
"बगल में"	:'Preposition',
"बराबर"	:'Preposition',
"बलबूते"	:'Preposition',
"बाद"	:'Preposition',
"बाहर"	:'Preposition',
"बिना"	:'Preposition',
"भर"	:'Preposition',
"भांति"	:'Preposition',
"भीतर"	:'Preposition',
"मात्र"	:'Preposition',
"मारे"	:'Preposition',
"में"	:'Preposition',
"योग्य"	:'Preposition',
"लिए"	:'Preposition',
"लेकिन"	:'Preposition',
"विपरीत"	:'Preposition',
"विरूद्ध"	:'Preposition',
"संग"	:'Preposition',
"समान"	:'Preposition',
"समेत"	:'Preposition',
"सहारे"	:'Preposition',
"साथ"	:'Preposition',
"सामने"	:'Preposition',
"सिवा"	:'Preposition',
"सिवाय"	:'Preposition',
"से"	:'Preposition',
"से पहले"	:'Preposition',
"हेतु"	:'Preposition',
"को":'Preposition',
    }