dict_pronoun={"हम"	:'Pronoun',"जिनकी":'Pronoun',"खुद":'Pronoun',"वो":'Pronoun',"उनका":'Pronoun',
"हमने "	:'Pronoun',"उन्हें":'Pronoun',"उसे":'Pronoun',
"हमें"	:'Pronoun',
"तू"	:'Pronoun',
"तुम"	:'Pronoun',
"आप"	:'Pronoun',
"मैं"	:'Pronoun',
"वह"	:'Pronoun',
"वे"	:'Pronoun',
"मुझे":'Pronoun',
"मुझसे":'Pronoun',
"मैंने":'Pronoun',
                  "अपना": 'Pronoun',
                  "आप": 'Pronoun',
                  "आप लोग": 'Pronoun',
                  "आप सब": 'Pronoun',
                  "आपका": 'Pronoun',
                  "आपकी": 'Pronoun',
                  "आपके": 'Pronoun',
                  "तु": 'Pronoun',
                  "तुम ": 'Pronoun',
                  "तुम सब": 'Pronoun',
                  "तुम्हारा": 'Pronoun',
                  "तुम्हारी": 'Pronoun',
                  "तुम्हारे": 'Pronoun',
                  "तुम्हें": 'Pronoun',
                  "तू": 'Pronoun',
                  "मुझे": 'Pronoun',
                  "मै": 'Pronoun',
                  "मैं": 'Pronoun',
                  "मैने": 'Pronoun',
                  "हम": 'Pronoun',
                  "हम को": 'Pronoun',
                  "हम ने": 'Pronoun',
                  "हम लोग": 'Pronoun',
                  "हम सब": 'Pronoun',
                  "हमने": 'Pronoun',
                  "हमारा": 'Pronoun',
                  "हमारी": 'Pronoun',
                  "हमारे": 'Pronoun',
                  "हमे": 'Pronoun',
                  "हमें": 'Pronoun',
                  "मेरी": 'Pronoun',
                  "अपना": 'Pronoun',
                  "मेरा": 'Pronoun',
                  "खनि": 'Pronoun',
                  "मेरे": 'Pronoun',
                  "अपने आप": 'Pronoun',
                  "स्वयं": 'Pronoun',
                  "ख़ुद": 'Pronoun',

}